### ISSUE TITLE
Participate in MSU Annual Video Codecs Comparison 2019

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-HEVC#109]
Moscow State University is soon (deadline March 1) starting with it's yearly codec review, it would be great to have SVT-HEVC included in it.
- [MSU Annual Video Codecs Comparison 2019: Call for codecs](http://www.compression.ru/video/codec_comparison/call_for_codecs_19.html)

**Comment by tianjunwork** [comment]
Maybe next year:)
