### ISSUE TITLE
EbInitEncoder takes too much time(1.8s~2.0.s) on Xeon-E5

### ISSUE THREAD

**Issue by daijh** [OpenVisualCloud/SVT-HEVC#139]
EbInitEncoder takes too much time(1.8s) on Ubuntu16.04 v1.3.0 Xeon-E5.
After some debug, parsing /proc/cpuinfo costs most of time(1.3s). Because E5 has 72 cores ,and big cpuinfo file.

[e5-cpuinfo.txt](https://github.com/intel/SVT-HEVC/files/2944105/e5-cpuinfo.txt)

**Comment by hassount** [comment]
In SVT_HEVC all of the memory is being allocated at init time. The higher the number of cores, the higher the memory that's needed.

**Comment by daijh** [comment]
@hassount 
Thanks for your reply. Understood that high memory allocation time is expected.
But this performance issue is that slow file operation on "/proc/cpuinfo" cost ~1300ms with "open/read"; After switch to "fopen/fgets", the time is only ~5ms.

I will prepare a pull request, hope you can help to review. Thanks a lot.

**Comment by tianjunwork** [comment]
@daijh Thanks for debugging the issue. It seems a regression. @dseah-intel is that ok to use fopen?
