### ISSUE TITLE
Invalid FPS in FPS: SVT Encoder error

### ISSUE THREAD

**Issue by vasavee** [OpenVisualCloud/SVT-HEVC#147]
Command line used:
 ./ffmpeg -i  POS-3k.mp4  -c:v libsvt_hevc -preset 10 -tune 1 -rc 0 -qp 31 -f null -
./ffmpeg -i POS-3k.mp4 -c:v libsvt_hevc -preset 10 -tune 0 -rc 1 -b:v 5000000 -f null -

No changes made to SVT config, all parameters controlled from command line.
Below is the ffmpeg log:</h3>
<body>

- ffmpeg version n4.1-64-gbcfd82b0be Copyright (c) 2000-2019 the FFmpeg developers
-   built with gcc 7 (GCC)
-   configuration: --enable-libsvthevc
-   libavutil      56. 22.100 / 56. 22.100
-   libavcodec     58. 35.100 / 58. 35.100
-   libavformat    58. 20.100 / 58. 20.100
-   libavdevice    58.  5.100 / 58.  5.100
-   libavfilter     7. 40.101 /  7. 40.101
-   libswscale      5.  3.100 /  5.  3.100
-   libswresample   3.  3.100 /  3.  3.100
- Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'POS-3k.mp4':
-   Metadata:
-     major_brand     : isom
-     minor_version   : 512
-     compatible_brands: isomiso2avc1mp41
-     encoder         : Lavf58.22.100
-   Duration: 00:02:19.20, start: 0.000000, bitrate: 89999 kb/s
-     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 3840x2160, 89995 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
-     Metadata:
-       handler_name    : VideoHandler
- Stream mapping:
-   Stream #0:0 -> #0:0 (h264 (native) -> hevc (libsvt_hevc))
- Press [q] to stop, [?] for help
- SVT [version]:  SVT-HEVC Encoder Lib v1.3.0
- SVT [build]  :  GCC 7.3.1        64 bit
- LIB Build date: Feb 11 2019 14:15:51
- -------------------------------------------
- SVT [Error]: Instance 1: The minimum allowed Profile number is 1
- SVT [Error]: Instance 1 : Invalid FPS in VPS flag [0 - 1]
- [libsvt_hevc @ 0x39148c0] Error setting encoder parameters
- Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
- Conversion failed!
- </body>

**Comment by tianjunwork** [comment]
Hi @jsunintel, could you take a look?

**Comment by jsunintel** [comment]
OK

**Comment by tianjunwork** [comment]
@vasavee is the error fixed by jsunintel's answer? If yes, please close this issue.

**Comment by vasavee** [comment]
> You didn't set width, height and bitrate explicitly, but the mp4 file contains such information, and the decoded width, height and bitrate from mp4 files are passed to SVT HEVC and used to control the encoding process.
> 
> For the dimensions 3840x2160, only preset [0-9] is supported.

I see in the encoding guide that 4k can handle until encMode 12 for subjective and encMode 10 for objective. What am I missing here?

**Comment by tianjunwork** [comment]
Hi @jsunintel, is this issue done? Please help to follow up. Thx.

**Comment by jsunintel** [comment]
Hi @hassount，in the lib & app, the resolutions are set as below:

#define INPUT_SIZE_576p_TH				0x90000		// 0.58 Million   
#define INPUT_SIZE_1080i_TH				0xB71B0		// 0.75 Million
#define INPUT_SIZE_1080p_TH				0x1AB3F0	// 1.75 Million
#define INPUT_SIZE_4K_TH				0x29F630	// 2.75 Million  

However, 1920x1080 equals 2073600 and is much bigger than 1750000 (0x1AB3F0), and 3840x2160 equals 8294400 is also much bigger than 2750000 (0x29F630). Are those wrong settings? Could I change those to the values 2073600 & 2750000?

**Comment by lijing0010** [comment]
@jsunintel ,that value is for encoded frame size, so normally it should be OK.
But it hasn't considered for 8K and doesn't work for 8K when qp is small.
I remember I've changed it before, seems still there...

**Comment by lijing0010** [comment]
@jsunintel I think this is just a rough number.
eg: if 720P, the size is E1000 < 1AB3F0, then it's treated as  INPUT_SIZE_1080i_RANGE.
it doesn't need to be 1080P to lie in the INPUT_SIZE_1080p_RANGE.
Anyway you can change those numbers, but it probably will not cause too much different

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel I think this is just a rough number.
> eg: if 720P, the size is E1000 < 1AB3F0, then it's treated as INPUT_SIZE_1080i_RANGE.
> it doesn't need to be 1080P to lie in the INPUT_SIZE_1080p_RANGE.
> Anyway you can change those numbers, but it probably will not cause too much different

"4k can handle until encMode 12 for subjective and encMode 10 for objective".

Hi @lijing0010, is such a limitation set by the SW purely, which means we could enable M12 to all supported resolutions technically?

**Comment by lijing0010** [comment]
There is a table for all the supported modes and resolutions.
Not all the combination are valid.
https://01.org/sites/default/files/documentation/scalable_video_technology_for_the_visual_cloud.pdf

**Comment by tinskip** [comment]
Maybe it should "just work" by assuming you want the output to be the same resolution as the input? Just a crazy thought.
