### ISSUE TITLE
Option for repeat SPS/PPS headers

### ISSUE THREAD

**Issue by pryg-skok** [OpenVisualCloud/SVT-HEVC#150]
Is there any option in encoder which can control repetition of bitstream headers (SPS/PPS)?
The stream cannot be played if player starts playing in middle of stream after ffmpeg, compiled with svt_hevc plugin. If it starts playing from start of dump - it plays well.

Can you provide a patch or point me in right direction with option?

**Comment by tianjunwork** [comment]
@pryg-skok SVT does has this api to request sps/pps.
EB_API EB_ERRORTYPE EbH265EncStreamHeader(
    EB_COMPONENTTYPE           *h265EncComponent,
    EB_BUFFERHEADERTYPE       **outputStreamPtr);
@jsunintel Could you help to integrate with ffmpeg?

**Comment by pryg-skok** [comment]
Ok! These headers definitely inserted at stream's start, but it is useless for endless streams encoding.

**Comment by tianjunwork** [comment]
Since picture parameters are of NO change on the fly. FFmpeg plugin can save the vps/sps/pps at init time. And return the data when requested. 
Do you think it works?

**Comment by pryg-skok** [comment]
I guess it should work, until you implement function like "change_codec_params_on_fly" :) 
But you need also properly calculate bytes which will be used by headers, because when one using VBV encoding (the bitrate control which also must work for endless streams encoding) this may leads to bitrates overflow.
BTW, is VBV encoding (HRD for HEVC) working now?

**Comment by tianjunwork** [comment]
VBV is in the backlog: https://trello.com/b/0xqT4xeY/svt-hevc.
There is no resource to implement for the next release. 
We welcome the contribution from the community:)

Please work with @jsunintel to use EbH265EncStreamHeader for now. Thx.

**Comment by pryg-skok** [comment]
I see, thank you!

It's strange that VBV-encoding not implemented and even not in roadmap yet, because in general it means that this encoder cannot be used for encoding videos for streaming due to bitrate fluctuations.

Also feature like gstreamer plugin can be implemented by community but VBV mode quite subtle mechanism and maybe its better to be developed within core team.

**Comment by tianjunwork** [comment]
The core team also works nonstop on AV1 and VP9 encoder. If time allows and depends on the priority, backlog feature can be pulled in.
Btw, Gstreamer plugins for all SVT encoders will soon be released.

**Comment by tianjunwork** [comment]
Hi @pryg-skok, with this PR https://github.com/OpenVisualCloud/SVT-HEVC/pull/250, IntraRefreshType API is extended to insert VPS/SPS/PPS for every N GOP. Please let us know if you have further request.
