### ISSUE TITLE
The libsvt_hevc library used by ffmpeg doesn't have the interface to specify pixel format yuv422p

### ISSUE THREAD

**Issue by tsubasawing123456** [OpenVisualCloud/SVT-HEVC#151]
When typing the command: ./ffmpeg xxx -c:v libsvt_hevc -pix_fmt yuv422p xxx, we would get the warning:

Incompatible pixel format 'yuv422p' for codec 'libsvt_hevc', auto-selecting format 'yuv420p'

Although the format yuv422p has already been implemented by SVT-HEVC commit:

commit 51c5f427ad28320ec6765f9406ae02b25ca4c93d
Author: lijing0010 <jingl3@hotmail.com>
Date:   Fri Feb 22 15:07:43 2019 +0800

    Add 422/444 support (#105)

    * Add 422/444 support in buf desc and PCS

    Signed-off-by: Jing Li <jing.b.li@intel.com>

**Comment by tianjunwork** [comment]
Hi @jsunintel please expose the new feature to ffmpeg. Thx.

**Comment by Ilya87** [comment]
@tsubasawing123456 as a workaround you can use (if your OS is Linux) the following subsitution instead of input file: <(ffmpeg -i videofile -f rawvideo -pix_fmt yuv422p - 2>/dev/null)

**Comment by jsunintel** [comment]
Will add.
