### ISSUE TITLE
Abnormal outputs for both ffmpeg and SvtHevcEncApp when tune=0 and qp=10

### ISSUE THREAD

**Issue by DanielOutlook** [OpenVisualCloud/SVT-HEVC#153]
A problem has been found that abnormal outputs are generated from both ffmpeg and SvtHevcEncApp when qp=10 and tune=0. 
The testing resolution of the video clip is 3840x2160, and some other sizes of videos, such as 4096x 2160, are also tested. So far, this problem happens on 4K streams. 
The testing video clip at 3840x2160 is attached as a zip file([abc033.zip](https://github.com/OpenVisualCloud/SVT-HEVC/files/2981900/abc033.zip)), and since its format is "ts", it needs to be converted to YUV first. The command line for decoding is:
`ffmpeg -i build/lin_x64/output/hevce_vmaf-cqp-svt/abc033.ts -c:v rawvideo -f rawvideo  build/lin_x64/output/hevce_vmaf-cqp-svt/abc033.ts-2.yuv -y 2>&1`.
In this circumstance, for both ffmpeg and SvtHevcEncApp, the output videos are mostly covered by green colour. The command line for ffmpeg is shown below: 
`ffmpeg -r 30 -video_size 3840x2160 -pixel_format yuv420p -f rawvideo -i /home/media/debug_test/dcg_media-openmediaframework-ffmpeg-test-framework/build/lin_x64/output/hevce_vmaf-cqp-svt/abc033.ts-2.yuv -c:v libsvt_hevc -rc 0 -qp 10 -preset 1 -vframes 10 -r 30 -tune 0 -f hevc build/lin_x64/output/hevce_vmaf-cqp-svt/abc033.ts-2.yuv.hevc -y 2>&1`
And the command for SvtHevcEncApp is: 
`SvtHevcEncApp -i /home/media/debug_test/dcg_media-openmediaframework-ffmpeg-test-framework/build/lin_x64/output/hevce_vmaf-cqp-svt/abc033.ts-2.yuv -w 3840 -h 2160 -fps-num 30 -fps-denom 1 -encMode 1 -n 10 -q 10 -rc 0 -tune 0  -b build/lin_x64/output/hevce_vmaf-cqp-svt/abc033.ts-2.yuv.svtapp.hevc`
In ffmpeg, parameter "-qp 10" is the same as "-q 10" in SvtHevcEncApp, "-preset" in ffmpeg and "-encMode" are the same, "-vframes" in ffmpeg and "-n" also have the same meaning. 
Another finding is, if the parameters "-preset 1" and "-encMode 1" are removed from ffmpeg and SvtHevcEncApp respectively, the output video images are not covered by green colour, but they are blur, which is not normal, either.

**Comment by tianjunwork** [comment]
@DanielOutlook Thanks for the report. We will check it out.

**Comment by tianjunwork** [comment]
@DanielOutlook issue is confirmed. Thx for reporting.
4k input, tune 0, encMode 0-6, bitstream is corrupted. With tune 1/2, bitstream is fine. I didn't verify other resolution.
I didn't see the video is blur removing "-encMode 1"(default is 9) though.

**Comment by lijing0010** [comment]
@tianjunwork , what platform are you using?(and which version are you using?)
I couldn't reproduce it on my side with the same file and command on the latest commit(f924ff9b09a62737154ce4565c0ee3ffba5166b3)
Is there anything I need to take care of?

**Comment by DanielOutlook** [comment]
@lijing0010 Hello. I use CentOS 7.4 on Intel NUC (skeleton) in my office.

**Comment by tianjunwork** [comment]
@lijing0010  GCC 8.1.0  64bit, Ubuntu 16.04, SVT tip.
./SvtHevcEncApp -i ../../../ffmpeg/abc033.ts-2.yuv -w 3840 -h 2160 -fps 30 -n 10 -q 10 -rc 0 -tune 0 -encMode 0 -b abc033.ts-0.yuv.1.hevc

**4k input, tune 0, encMode 0-6, bitstream is corrupted. With tune 1/2, bitstream is fine.**
