### ISSUE TITLE
The encoded SVT-HEVC clips has difference between AsmType enabled and disabled

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-HEVC#161]
Take YUV P420/P422/P444 file as input, then use application SvtHevcEncApp to do SVT-HEVC encode with AsmType enabled and disabled, the generated two SVT-HEVC clips has difference.

List a pair command line as example:
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P444.yuv  -b bitstreams/asm_test_M5_Fallout4_1920x1080_8bit_60Hz_P444_Q34_VMAF_0.265  -errlog bitstreams/asm_test_M5_Fallout4_1920x1080_8bit_60Hz_P444_Q34_VMAF_0.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 40  -color-format 3  -compressed-ten-bit-format 0  -encMode 5  -q 34  -rc 0  -tune 2  **-asm 0**
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P444.yuv  -b bitstreams/asm_test_M5_Fallout4_1920x1080_8bit_60Hz_P444_Q34_VMAF_1.265  -errlog bitstreams/asm_test_M5_Fallout4_1920x1080_8bit_60Hz_P444_Q34_VMAF_1.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 40  -color-format 3  -compressed-ten-bit-format 0  -encMode 5  -q 34  -rc 0  -tune 2  **-asm 1**

MD5 check of two generated SVT-HEVC clips:
asm_test_M5_Fallout4_1920x1080_8bit_60Hz_P444_Q34_VMAF_1.265: dfb62b97975b34bf9b9ae46e420968c3
asm_test_M5_Fallout4_1920x1080_8bit_60Hz_P444_Q34_VMAF_0.265: 20fbe4858790a693d32bb5863ee1ca39

**Comment by tianjunwork** [comment]
Hi @liweki Thx for posting the issue. I verified the two bitstreams are identical. I simply use a binary viewer application to compare the two bitstreams. 
Could you use a binary viewer like HxD to verify your bitstream? If you still see the difference, let me know.

**Comment by liweki** [comment]
Hi, @tianjunwork,
I use HxD and Beyond Compare to compare the two bitstreams, the difference begins from offset 0001D3E0.

![bitstreams_difference](https://user-images.githubusercontent.com/46477459/55061479-d59eda80-50ae-11e9-85e8-402470564f96.png)

**Comment by tianjunwork** [comment]
WIP by https://github.com/OpenVisualCloud/SVT-HEVC/pull/195

**Comment by Austin-Hu** [comment]
Hi @liweki ,

We confirmed that the issue can be fixed by the PR [#195](https://github.com/OpenVisualCloud/SVT-HEVC/pull/195/), so please close this issue after the PR #195 is merged and your verification. Thanks!
