### ISSUE TITLE
Add --version output for the stand-alone encoders and ffmpeg's -encoders listing

### ISSUE THREAD

**Issue by krcroft** [OpenVisualCloud/SVT-HEVC#171]
For the ffmpeg patch, here's an example: 

`ffmpeg -version`

```
ffmpeg version n4.1.3-1-gec82b3ecbb Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
configuration: --enable-libsvthevc --disable-vaapi --enable-libopus
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libsvthevcenc   X.  Y.Z   /  X.  Y.Z
```

**Comment by tianjunwork** [comment]
Hi @krcroft  version info is printed when running SvtHevcEncApp.
SVT [version]:	SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :	GCC 7.3.1	 64 bit
LIB Build date: Apr  2 2019 20:30:31

**Comment by jsunintel** [comment]
> 
> 
> Hi @jsunintel, Could you add the info here? libsvthevcenc X. Y.Z / X. Y.Z

OK.

**Comment by krcroft** [comment]
@jsunintel, hmm.. indeed.  It's also too bad versions are indicated in the output from `ffmpeg -decoders` and `ffmpeg -encoders`.  That said, these are just free form strings, and we see a variety of how thoroughly a codec is described (or lack-there-of).  For example, RealAudio lists their version, bit rate, and a codec signature where as Sonic lists.. just Sonic!

```
 A..... real_144             RealAudio 1.0 (14.4K) (codec ra_144)
 A..X.. s302m                SMPTE 302M
 A..... sbc                  SBC (low-complexity subband codec)
 A..X.. sonic                Sonic
```
Given it's a free-form string without version restrictions, is there any harm in providing some major or minor versioning for the SVT codecs?  The rate of development is non-trivial and benefits in both quality and performance are happening rapidly, so an easy way to query this is extremely helpful.  

```
 V..... libsvt_hevc          SVT-HEVC(Scalable Video Technology for HEVC encoder) (v1.3.0) (codec hevc)
 V..... libsvt_av1           SVT-AV1 (Scalable Video Technology for AV1 encoder) (v0.8.1) (codec av1)
```
Or something like that ..

**Comment by krcroft** [comment]
Regarding the stand-alone binaries, --help indicates ` --version  output version information and exit` however I get:
```
/usr/local/bin/SvtHevcEncApp --version
-------------------------------------------
SVT-HEVC Encoder
SVT [Error]: Instance 1: Invalid Input File
Unprocessed tokens:  --version 

Error in configuration, could not begin encoding! ... 
Run /usr/local/bin/SvtHevcEncApp -help for a list of options
Encoder finished
```

**Comment by tianjunwork** [comment]
Hi @krcroft, exposing version info should be doable through `ffmpeg -encoders`.
`SvtHevcEncApp --version` will fail because it doesn't have --version parameter.

**Comment by jsunintel** [comment]
When doing encoding jobs by SVT, we have such information dumped by SVT lib.
'''
[]# ./ffmpeg -f rawvideo -s 960x400 -i /work/clips/matrix_1920x1080_250i.yuv -c:v libsvt_vp9 -preset 8 -an test8.ivf
ffmpeg version N-93635-g45fa3c9 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-libsvtvp9 --enable-libvpx
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 52.100 / 58. 52.100
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 49.100 /  7. 49.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
[rawvideo @ 0x2479600] Estimating duration from bitrate, this may be inaccurate
Input #0, rawvideo, from '/work/clips/matrix_1920x1080_250i.yuv':
  Duration: 00:00:54.00, start: 0.000000, bitrate: 115200 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 960x400, 115200 kb/s, 25 tbr, 25 tbn, 25 tbc
File 'test8.ivf' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libsvt_vp9))
Press [q] to stop, [?] for help
SVT [version]   : SVT-VP9 Encoder Lib v0.1.0
SVT [build]     : GCC 5.4.0      64 bit
LIB Build date: Apr 24 2019 14:43:51
'''

**Comment by krcroft** [comment]
@tianjunwork,
> SvtHevcEncApp --version will fail because it doesn't have --version parameter.

So I need to pass an additional `--version` parameter to the existing `--version` argument, like so: `SvtHevcEncApp --version --version`? (which appear extremely unintuitive).  It also doesn't work:

```
SvtHevcEncApp --version --version
-------------------------------------------
SVT-HEVC Encoder
SVT [Error]: Instance 1: Invalid Input File
Unprocessed tokens:  --version  --version 
```

@tianjunwork, can you copy and paste the exact --version invocation that produces your version string?

Some examples for reference for how typically **--version** works:

1. **x264 --version**
```
x264 0.148.x
(libswscale 4.0.0)
(libavformat 57.7.1)
(ffmpegsource 2.22.0.0)
built on Jun 19 2016, gcc: 5.3.1 20160413
x264 configuration: --bit-depth=8 --chroma-format=all
libx264 configuration: --bit-depth=8 --chroma-format=all
x264 license: GPL version 2 or later
```

2. **flac --version**
```
flac 1.3.2
```

3. **gzip --version**
```
gzip 1.6
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.                                                       
Copyright (C) 1993 Jean-loup Gailly.                                                                                
```

4. **oggenc --version**
oggenc from vorbis-tools 1.4.0


And so on.. I'm hoping your binaries (will soon) provide similar versioned information when passed the `--version` parameter.

**Comment by krcroft** [comment]
@jsunintel 
> When doing encoding jobs by SVT, we have such information dumped by SVT lib.

So you're saying that, to discover the SVT-version used in FFMPEG, the user needs to construct a valid encode job including providing valied media files, and launch it with sufficient correctness that FFMPEG eventually triggers the internal SVT library - and from there, the user can grep or inspect the output?

That's perhaps the most unintuitive and burdensome method I've every heard of to determine the version of problem.  How many users know how to construct a fully working FFMPEG encode job (including codec-selection) off the tops of their head?

Myself and @tianjunwork have already indicated adding SVT version details to the listing from `ffmpeg --encoders` and `ffmpeg --decoders` is perfectly suitable.  Hopefully this is doable.  Regards, Kevin

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel
> 
> > When doing encoding jobs by SVT, we have such information dumped by SVT lib.
> 
> So you're saying that, to discover the SVT-version used in FFMPEG, the user needs to construct a valid encode job including providing valied media files, and launch it with sufficient correctness that FFMPEG eventually triggers the internal SVT library (and actually initiate the encode and incurred CPU & resource usage) - and from there, the user can Ctrl-C the job and then grep or inspect the output?
> 
> That's perhaps the most unintuitive and burdensome method I've every heard of to determine the version of a program or library! On top of that, how many users casually know how to construct a fully working FFMPEG encode command line and arguments (including codec-selection) off the top of their head?
> 
> Myself and @tianjunwork have already indicated adding SVT version details to the listing from `ffmpeg --encoders` and `ffmpeg --decoders` is perfectly suitable. Hopefully this is doable. Regards, Kevin

ffmpeg -encoders/-decoders is not for dumping encoders/decoders' version information, but only the available encoders/decoders' name and type. Check the code lines and a typical output example, which shows no version. It's never suitable to change any routine of FFmpeg's.

    for (i = 0; i < nb_codecs; i++) {
        const AVCodecDescriptor *desc = codecs[i];
        const AVCodec *codec = NULL;

        while ((codec = next_codec_for_id(desc->id, codec, encoder))) {
            printf(" %c", get_media_type_char(desc->type));
            printf((codec->capabilities & AV_CODEC_CAP_FRAME_THREADS) ? "F" : ".");
            printf((codec->capabilities & AV_CODEC_CAP_SLICE_THREADS) ? "S" : ".");
            printf((codec->capabilities & AV_CODEC_CAP_EXPERIMENTAL)  ? "X" : ".");
            printf((codec->capabilities & AV_CODEC_CAP_DRAW_HORIZ_BAND)?"B" : ".");
            printf((codec->capabilities & AV_CODEC_CAP_DR1)           ? "D" : ".");

            printf(" %-20s %s", codec->name, codec->long_name ? codec->long_name : "");
            if (strcmp(codec->name, desc->name))
                printf(" (codec %s)", desc->name);

            printf("\n");
        }
    }

```
 V..... a64multi             Multicolor charset for Commodore 64 (codec a64_multi)
 V..... a64multi5            Multicolor charset for Commodore 64, extended with 5th color (colram) (codec a64_multi5)
 V..... alias_pix            Alias/Wavefront PIX image
 V..... amv                  AMV Video
 V..... apng                 APNG (Animated Portable Network Graphics) image
 V..... asv1                 ASUS V1
 V..... asv2                 ASUS V2
 V..... avrp                 Avid 1:1 10-bit RGB Packer
 V..X.. avui                 Avid Meridien Uncompressed
 V..... ayuv                 Uncompressed packed MS 4:4:4:4
 V..... bmp                  BMP (Windows and OS/2 bitmap)
 V..... cinepak              Cinepak
 V..... cljr                 Cirrus Logic AccuPak
 V.S... vc2                  SMPTE VC-2 (codec dirac)
 VFS... dnxhd                VC3/DNxHD
 V..... dpx                  DPX (Digital Picture Exchange) image
 VFS... dvvideo              DV (Digital Video)
 V.S... ffv1                 FFmpeg video codec #1
 VF.... ffvhuff              Huffyuv FFmpeg variant
 V..... fits                 Flexible Image Transport System
 V..... flashsv              Flash Screen Video
 V..... flashsv2             Flash Screen Video Version 2
 V..... flv                  FLV / Sorenson Spark / Sorenson H.263 (Flash Video) (codec flv1)
 V..... gif                  GIF (Graphics Interchange Format)
 V..... h261                 H.261
 V..... h263                 H.263 / H.263-1996
 V.S... h263p                H.263+ / H.263-1998 / H.263 version 2
 V..... h264_vaapi           H.264/AVC (VAAPI) (codec h264)
 V..... libsvt_hevc          SVT-HEVC(Scalable Video Technology for HEVC) encoder (codec hevc)
 V..... hevc_vaapi           H.265/HEVC (VAAPI) (codec hevc)
 VF.... huffyuv              Huffyuv / HuffYUV
 V..... jpeg2000             JPEG 2000
...
```

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel
> 
> > When doing encoding jobs by SVT, we have such information dumped by SVT lib.
> 
> So you're saying that, to discover the SVT-version used in FFMPEG, the user needs to construct a valid encode job including providing valied media files, and launch it with sufficient correctness that FFMPEG eventually triggers the internal SVT library (and actually initiate the encode and incurred CPU & resource usage) - and from there, the user can Ctrl-C the job and then grep or inspect the output?
> 
> That's perhaps the most unintuitive and burdensome method I've every heard of to determine the version of a program or library! On top of that, how many users casually know how to construct a fully working FFMPEG encode command line and arguments (including codec-selection) off the top of their head?
> 
> Myself and @tianjunwork have already indicated adding SVT version details to the listing from `ffmpeg --encoders` and `ffmpeg --decoders` is perfectly suitable. Hopefully this is doable. Regards, Kevin

SVT HEVC lib is connected to FFmpeg by the plugin. FFmpeg itself has no responsibility in tracking the 3rd party libraries' version. I was just showing you a method to get the information you asked. The formal methods to get the version of a shared library are:
```
[]# cat /usr/local/lib/pkgconfig/SvtHevcEnc.pc
prefix=/usr/local
includedir=${prefix}/include/svt-hevc
libdir=${prefix}/lib

Name: SvtHevcEnc
Description: SVT (Scalable Video Technology) for HEVC encoder library
Version: 1.3.0
Libs: -L${libdir} -lSvtHevcEnc -lpthread
Cflags: -I${includedir}
```

Or:
```
[]# readelf -h /usr/local/lib/libSvtHevcEnc.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x31cd0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          14398944 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         6
  Size of section headers:           64 (bytes)
  Number of section headers:         35
  Section header string table index: 34
```

**Comment by tianjunwork** [comment]
@krcroft the stand-alone encoder app doesn't have `--version` argument. All available arguments you can refer to the user guide. There is no usage like `SvtHevcEncApp --version --version`.
When running either standalone app or ffmpeg/gst plugin to perform encoding task, the underlining encoder lib will print version info like below:
SVT [version]:  SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :  GCC 8.1.0        64 bit
LIB Build date: Apr 16 2019 14:02:09
Could you justify the need of adding `-version` to the standalone app?

**Comment by Selur** [comment]
>Could you justify the need of adding -version to the standalone app?

Having a '-version' string would help GUI developers to adjust there gui in case options change etc.

**Comment by krcroft** [comment]
I am left dumbfounded why this project refuses to provide a `--version` argument for their stand alone command line encoder. 

A version flag allows users to know what version they are running, to compare encoding results with other versions, and to inform them if they wish to up or down grade their versions. 

These and many more benefits come with the ability to query version from a command line tool; its a best-practice and available in almost every Linux/Windows/BSD/OSX command line application.

**Comment by tianjunwork** [comment]
Hi @Selur, sorry for the late reply for being out of office. In my opinion, if you work with GUI, you need to invoke svt library directly. We now have EbApiVersion.h in the API folder that any application can use.

Hi @krcroft, Kevin, Thank you for your feedback :)
To be clear, we do have version info in the library which any application(SvtHevcEncApp, other GUI tools, ffmpeg, gst etc) can query.
Adding a "--version" interface for SvtHevcEncApp doesn't show much value since  "SVT [version]" is printed when running, which never causes issues for our bench marking task.
It is not something that we can't do. We will work on it based on priority.

**Comment by krcroft** [comment]
> Adding a "--version" interface for SvtHevcEncApp doesn't show much value since "SVT [version]" is printed when running, which never causes issues for our bench marking task.
It is not something that we can't do. We will work on it based on priority.

Just because the information can be derived in a round about way does not mean it's an acceptable solution. In the same way, it's also possible for you to walk-backward to get from A to B. Likewise, grep'ing and parsing strings from the runtime output text is also not the best way for users and script authors to pull version information.  

Adding `--version` and `--help` is command-line programming 101, so I appreciate you acknowledging the need for this and working it into your queue!

**Comment by 1480c1** [comment]
@hassount, would it be possible to add a `--version`, `-v`, and `--help` flags on all of the SVT encoders?
With `--version` and `-v` being the same and `--help` being the same as `-help`? 

It would help with new people considering almost all linux programs use `--` for long arguments and `-` for "short" single character arguments and so most people would try `./SvtHevcEncApp --help` first before reading the error message outputted by the encoder

**Comment by Selur** [comment]
@tianjunwork: Using the library is fine if you use the library. 
But a bunch of encoding frontends are guis for multiple encoders and use the< command line encoders of tools since it's often far less hassle for the users to switch out the command line encoder and for the frontend developer to maintain.

Instead of something like the usual `major.minor[.build[.revision]]` something like
```
(
  echo '/* Generated file, do not edit. */'
  echo  '#define APP_VERSION "'`git describe`'"'
  echo  '#define APP_VERSION_DATE "'`git log -n 1 --format=%ai`'"'
) > version.h
``` 
would be enough,...

If adding a '--version' option is a hassle to maintain, simply don't. I just think it's a usually low hanging fruit and folks which use scripts or encoding frontends which use cli have an easier life.

**Comment by tianjunwork** [comment]
Thank you all @krcroft @1480c1 @Selur for your quick response and feedback once again.
@Selur thanks for explaining how GUI encoding front end app works. I thought it uses the library directly. major.minor.build is actually easy to maintain for us. We will add it to SvtHevcEncApp.

**Comment by tianjunwork** [comment]
Hi @krcroft @1480c1 @Selur, please review #388 if possible. Thank you.

**Comment by Selur** [comment]
#388 Looks fine for me. :)

**Comment by krcroft** [comment]
#388 looks good.

**Comment by tianjunwork** [comment]
Thank you @krcroft @1480c1 @Selur reviewing the PR. I close this issue for now.
