### ISSUE TITLE
SvtHevcEnc not found using pkg-config

### ISSUE THREAD

**Issue by caoli5288** [OpenVisualCloud/SVT-HEVC#175]
> ./configure --cc=gcc-8 --disable-static --enable-shared --enable-libsvthevc
  ERROR: SvtHevcEnc not found using pkg-config

But do really can find it.
> pkg-config --libs SvtHevcEnc
  -lSvtHevcEnc -lpthread

config.log tail here:
> tail "ffbuild/config.log"
    3   long check_EbInitHandle(void) { return (long) EbInitHandle; }
    4   int main(void) { int ret = 0;
    5    ret |= ((intptr_t)check_EbInitHandle) & 0xFFFF;
    6   return ret; }
END /tmp/ffconf.hJxACFbb/test.c
gcc-8 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -std=c11 -fomit-frame-pointer -fPIC -pthread -I/usr/include/svt-hevc -c -o /tmp/ffconf.hJxACFbb/test.o /tmp/ffconf.hJxACFbb/test.c
gcc-8 -Wl,--as-needed -Wl,-z,noexecstack -I/usr/include/svt-hevc -o /tmp/ffconf.hJxACFbb/test /tmp/ffconf.hJxACFbb/test.o -lSvtHevcEnc -lpthread
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lSvtHevcEnc
collect2: error: ld returned 1 exit status

OS: debian8
How can I do for that?

**Comment by tianjunwork** [comment]
Hi @caoli5288 Did you follow the instruction exactly? https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/ffmpeg_plugin. 
Note: on Debian8 the path of of these two maybe different.
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
- export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig

**Comment by caoli5288** [comment]
@tianjunwork I make SvtHevcEnc use prefix `/usr`. Strange
After re-make with the usual prefix, everything is fine.
THX.
