### ISSUE TITLE
What do I lose without using the assembler in libsvt?

### ISSUE THREAD

**Issue by Jamaika1** [OpenVisualCloud/SVT-HEVC#176]
I use GCC with Windows. If I don't add file object EbPictureOperators_SSE2.asm, will the library work properly?

**Comment by 1480c1** [comment]
I do not think so

**Comment by 1480c1** [comment]
Are you using mingw or cygwin?

**Comment by Jamaika1** [comment]
I use MinGW 9.0.1 with site:
http://msystem.waw.pl/x265/
I test svt_hevc as encoder video svt_hevc and image libbpg on the doom9 forum:
http://forum.doom9.org/showthread.php?t=174300&page=7
I describes my problem with svt hevc in the libraries of the transformed opensource libbpg.
https://www.sendspace.com/file/lzsqp2
I mean the lines in files EbAvcStyleMcp_Intrinsic_SSE2.c and EbMcp_Intrinsic_SSE2.c:
`PictureCopyKernel_SSE2 (refPic, srcStride, dst, dstStride, puWidth, puHeight);`
and function Log2f in files object.
```
EB_U32 Log2f(EB_U32 x)
{
    EB_U32 y;
    EB_S32 n = 32, c = 16;

    do {
        y = x >> c;
        if (y > 0) {
            n -= c;
            x = y;
        }
        c >>= 1;
    } while (c > 0);

    return 32 - n;
}
```

**Comment by 1480c1** [comment]
Since you are using mingw-w64 without msys2 or any other system, I would recommend to get [nasm](https://www.nasm.us/) or [yasm](https://yasm.tortall.net/) (yasm is preferred by this project) and put them in the %PATH% and then run cmake. AFAIK, this project requires an assembler because there seems to be heavy use of assembly for some sse2 functions.

**Comment by Jamaika1** [comment]
Strange that only SSE2.

**Comment by tianjunwork** [comment]
Hi @Jamaika1, any update since then? How can we assist you further?

**Comment by Jamaika1** [comment]
What am I supposed to say? I create my codec in my own way. Probably with many mistakes.
http://forum.doom9.org/showthread.php?p=1875211#post1875211
