### ISSUE TITLE
Doesn't build with a modern version of gcc

### ISSUE THREAD

**Issue by wcochran** [OpenVisualCloud/SVT-HEVC#177]
Building C object Source/Lib/ASM_AVX2/CMakeFiles/ASM_AVX2.dir/EbComputeSAD_SadLoopKernel_AVX512.c.o
cc1: error: unrecognized command line option ‘-mno-sha’
cc1: error: unrecognized command line option ‘-mno-sgx’
[ 17%] Building C object Source/Lib/ASM_SSE2/CMakeFiles/ASM_SSE2.dir/EbComputeMean_Intrinsic_SSE2.c.o
Building C object Source/Lib/ASM_SSE4_1/CMakeFiles/ASM_SSE4_1.dir/EbTransforms_Intrinsic_SSE4_1.c.o
Building C object Source/Lib/ASM_AVX2/CMakeFiles/ASM_AVX2.dir/EbIntraPrediction_Intrinsic_AVX2.c.o
[ 17%] cc1: error: unrecognized command line option ‘-mno-sha’
cc1: error: unrecognized command line option ‘-mno-sgx’
Building C object Source/Lib/ASM_SSE2/CMakeFiles/ASM_SSE2.dir/EbCombinedAveragingSAD_Intrinsic_SSE2.c.o
cc1: error: unrecognized command line option ‘-mno-avx512f’
cc1: error: unrecognized command line option ‘-mno-avx512er’

$ uname
Linux

$ gcc --version
gcc (GCC) 7.2.1 20170915

$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
stepping	: 4
microcode	: 0x42d
q

**Comment by 1480c1** [comment]
Can you include your cflags (`echo $CFLAGS`) and the command line you used for cmake?

**Comment by wcochran** [comment]
$ echo $CFLAGS

empty

**Comment by tianjunwork** [comment]
Hi @wcochran, your E5-2650 is Sandy Bridge which doesn't satisfy our HW requirement Broadwell+. Please refer to the README.
FYI, Broadwell is a newer CPU microarchitecture than Sandy Bridge.
https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures
