### ISSUE TITLE
Added Visual Studio 16 2019 build support

### ISSUE THREAD

**Issue by tnti** [OpenVisualCloud/SVT-HEVC#183]
We only need to add a file generate_vs19.bat
The contents of the bat are as follows:

:: Copyright(c) 2018 Intel Corporation 
:: SPDX-License-Identifier: BSD-2-Clause-Patent

cmake ../.. "-GVisual Studio 16 2019" -A x64  -DCMAKE_ASM_NASM_COMPILER="yasm.exe" -DCMAKE_INSTALL_PREFIX=%SYSTEMDRIVE%\svt-encoders -DCMAKE_CONFIGURATION_TYPES="Debug;Release"
pause

@lijing0010  @hassount @tianjunwork

**Comment by tianjunwork** [comment]
@tnti Thanks:)
VS 2019 is just out for preview. We will add the support after official release.
By the way, did you have a chance to test build/run with vs 2019?

**Comment by tnti** [comment]
@tianjunwork  
I have installed vs2019 and built it successfully.
Vs2019 has been officially released in April.
Svt-av1 was successfully constructed in the same way as svt-vp9.

**Comment by tianjunwork** [comment]
@tnti That's great. Thx. Would you like to submit the PR since you already have it?

**Comment by 1480c1** [comment]
I can do one with variable generator so that there is only one batch script that can generate for 2019 and 2017 if that would be okay. I am currently doing one for SVT-AV1

**Comment by tianjunwork** [comment]
@1480c1 Sure, sounds good. Thank you.

**Comment by tnti** [comment]
@1480c1 
Thank you.

**Comment by 1480c1** [comment]
It's best to keep an issue open until there is something to actually address it (pr or something) so that way it can stay as a reminder of what is still being worked on

**Comment by tnti** [comment]
@1480c1 
 OK.
