### ISSUE TITLE
 SVT-HEVC encoder errors from x265

### ISSUE THREAD

**Issue by lupan2005** [OpenVisualCloud/SVT-HEVC#196]
I followed the instruction from https://x265.readthedocs.io/en/default/svthevc.html and able to build x265 with SVT-HEVC successfully.  But when I ran the new built x265, I got the following errors:
$ x265/build/linux/x265 --y4m tearsofsteel-4k.y4m --svt tearsofsteel-4k-svt.mp4
y4m  [info]: 4096x1714 fps 24/1 i420p8 frames 0 - 17619 of 17620
raw  [info]: output file: tearsofsteel-4k-svt.mp4
x265 [info]: HEVC encoder version 3.0+35-gc47874b
x265 [info]: build info [Linux][GCC 5.4.0][64 bit] 8bit
SVT [version]:  SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :  GCC 5.4.0 20160609       64 bit
LIB Build date: May 14 2019 17:07:15
-------------------------------------------
SVT [Error]: Instance 1 : Invalid tile column count
SVT [Error]: Instance 1 : Invalid tile row count
x265 [error]: SVT-HEVC Encoder: Error while configuring encoder parameters
x265 [error]: failed to open encoder

What could be the problem?   How to fix it?

Thanks

Lu

**Comment by tianjunwork** [comment]
Hi @lupan2005, TileRowCount and TileColumnCount are new APIs recently added to SVT to support tile-based encoding. 
In x265, source/common/param.cpp x265_param_default(), they are initialized to be 0 which is an invalid value. The minimum is 1 means the whole frame is one tile.
Could you post this issue to x265? Thank you.

**Comment by lupan2005** [comment]
Hi Tianjunwork,

Thanks for your info!
I could not find the TileRowCount and TileColumnCount in x265_param_default().  Which parameters related with them?
I do not how to post the issue to x265.   Could please send me the link?

Thanks

Lu

**Comment by tianjunwork** [comment]
Hi @lupan2005 ,

SVT master now has TileRowCount and TileColumnCount as part of EB_H265_ENC_CONFIGURATION. 
See https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/Source/API/EbApi.h line 327.
The svtParam buffer is memset to 0 in x265_param_default(). 
Yes, you could not find them in x265 master which is based on a svt commit without tile encoding. 

Please use this mailing list to communicate with x265:
https://bitbucket.org/multicoreware/x265/wiki/Home
Mailing list x265-devel@videolan.org

**Comment by lupan2005** [comment]
Thanks for the quick reply!

So you mean that x265 does not support the tile encoding for now, correct?

Ok, I will file the issue to x265.

Thanks again!

Lu

**Comment by tianjunwork** [comment]
Np:)
Yes, source/common/param.cpp should assign a valid value for the new SVT APIs.
Please report to x265. Thank you:)

**Comment by lupan2005** [comment]
Update:

I found the place to file the issue for x265:
https://bitbucket.org/multicoreware/x265/issues?status=new&status=open

**Comment by tianjunwork** [comment]
Thanks for letting me know.
https://bitbucket.org/multicoreware/x265/issues/496/svt-hevc-encoder-errors-from-x265
