### ISSUE TITLE
How to use -nch of SvtHevcEncApp?

### ISSUE THREAD

**Issue by vuiseng9** [OpenVisualCloud/SVT-HEVC#197]
From BKC in the user guide, for N channel encoding, it is recommended to use parallel instances of the SvtHevcEncApp. I wonder what is the usage of -nch? could you provide an example? if we use -nch 2, how do we specify parameters for 2nd channel?

Along same line, can we feed multiple .cfg where each corresponds to a channel?

Thank you!

**Comment by tianjunwork** [comment]
Hi @vuiseng9 , multi-instance support is documented in README.md.
The multi-instance functionality is a demo feature implemented in the SVT-HEVC Encoder sample application **as an example of one sample application using multiple encoding libraries**. Encoding using the multi-instance support is limited to only 6 simultaneous streams. For example two channels encoding: SvtHevcEncApp.exe -nch 2 -c firstchannel.cfg secondchannel.cfg

**Comment by vuiseng9** [comment]
@tianjunwork  Thank you!! I missed this readme as I was mainly searching in the ```doc/svt-hevc_encoder_user_guide.md```
