### ISSUE TITLE
Make AppVeyor project public

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-HEVC#198]
For some reason

- https://ci.appveyor.com/project/OpenVisualCloud/SVT-AV1

is accessible, but 

- https://ci.appveyor.com/project/OpenVisualCloud/SVT-VP9
- https://ci.appveyor.com/project/openvisualcloud/SVT-HEVC

are not ("Project not found or access denied.")

**Comment by tianjunwork** [comment]
@EwoutH those two links are working now. Thx for reporting.
