### ISSUE TITLE
Only first IDR frame have SEI info

### ISSUE THREAD

**Issue by whuigithub** [OpenVisualCloud/SVT-HEVC#201]

**Comment by whuigithub** [comment]
Hi SVT Devs:
    I enable the SVT hdr function and write the hdr metadata info into sei.
    but i found only first IDR picture have SEI info.
    What method do I have to get sei information write to other IDR picture.

**Comment by whuigithub** [comment]
Another question, can the encoding parameters change on fly? For example, I don't know the HDR metadata information when I call EbH265EncSetParameter.

**Comment by tianjunwork** [comment]
> Hi SVT Devs:
> I enable the SVT hdr function and write the hdr metadata info into sei.
> but i found only first IDR picture have SEI info.
> What method do I have to get sei information write to other IDR picture.

Hi @whuigithub, before we make plan to support it, could you try FFmpeg Bitstream Filters to insert SEI to unblock you? https://ffmpeg.org/ffmpeg-bitstream-filters.html#toc-hevc_005fmetadata.
No, encoding parameters can't be changed on the fly.

**Comment by tianjunwork** [comment]
Hi @whuigithub, before we make plan to support it, could you try FFmpeg Bitstream Filters to insert SEI to unblock you? https://ffmpeg.org/ffmpeg-bitstream-filters.html#toc-hevc_005fmetadata.
No, encoding parameters can't be changed on the fly.

**Comment by whuigithub** [comment]
ok，thanks, I plan call EncodeContentLightLevelSEI&EncodeMasteringDisplayColorVolumeSEI in EbH265EncStreamHeader API, save the Vps+Sps+Pps+SEI，call when I want to use them， am I doing this right?  or i could generate SEI info by myself.

**Comment by tianjunwork** [comment]
Hi @whuigithub Did you work through with your solution?

**Comment by weitec** [comment]
use ffmpeg bsf, for example
./ffmpeg  -I oceans.h264 -c:v copy -bsf:v h264_metadata=sei_user_data='086f3693-b7b3-4f2c-9653-21492feee5b8+hello' oceans.sei.h264
