### ISSUE TITLE
video corruption

### ISSUE THREAD

**Issue by tianjunwork** [OpenVisualCloud/SVT-HEVC#208]
video is corrupted with below command line:
https://github.com/OpenVisualCloud/SVT-HEVC/pull/206#issuecomment-498478295
./SvtHevcEncApp -i ./akiyo_cif.y4m -w 352 -h 288 -fps-num 30000 -fps-denom 1001 -b test.h265
Reproduced on both windows and linux on svt-hevc master.

**Comment by lijing0010** [comment]
is it y4m input or yuv input?

**Comment by tianjunwork** [comment]
@lijing0010 Thanks Jing. I verified yuv input with 352x288. Video is fine.
