### ISSUE TITLE
Sse2 assembly error.

### ISSUE THREAD

**Issue by tnti** [OpenVisualCloud/SVT-HEVC#217]
2>------ All rebuilds have been started: Project: ASM_SSE2, Configuration: Debug x64 ------
2>Building Custom Rule E:/SVT-HEVC/Source/Lib/ASM_SSE2/CMakeLists.txt
2>CMake does not need to re-run because E:/SVT-HEVC/Build/windows/Source/Lib/ASM_SSE2/CMakeFiles/generate.stamp is up-to-date.
2>Assembling EbGatherSaoStatistics16bit_SSE2.asm
2>D:\Program Files\CMake\share\cmake-3.14\Templates\MSBuild\nasm.targets(33,5): error MSB3721: Command ""yasm" -o "ASM_SSE2.dir\Debug\EbGatherSaoStatistics16bit_SSE2.obj" -fwin64 -I"E:\SVT-HEVC\Source\API\\" -I"E:\SVT-HEVC\Source\Lib\Codec\\" -I"E:\SVT-HEVC\Source\Lib\ C_DEFAULT\\" -I"E:\SVT-HEVC\Source\Lib\ASM_SSE2\\" -D"CMAKE_INTDIR="Debug"" -D"WIN64" "E:\SVT-HEVC\Source\Lib\ASM_SSE2\ EbGatherSaoStatistics16bit_SSE2.asm"" has exited with a return code of 1.
2> The operation of generating the project "ASM_SSE2.vcxproj" has been completed - failed.

The above is the error message provided by the vs2019 build.

**Comment by 1480c1** [comment]
do you have `yasm` in `PATH`? (try to type `yasm --version` in powershell or cmd)
Please print the output of `yasm --version` here

**Comment by tnti** [comment]
Is my update vs2019 causing the yasm path to change, the configuration file is wrong.
I have already solved it.
@1480c1  thank you.
