### ISSUE TITLE
fps output mismatch with ffprobe

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-HEVC#218]
Although the encoding window shows

``` none
Frame Rate
29.97 fps
```

ffprobe shows `Stream #0:0: Video: hevc (Main), yuv420p(tv), 352x288, 25 fps, 25 tbr, 1200k tbn, 25 tbc`

Shows both on `4.18.0-21-generic #22~18.04.1-Ubuntu` and mingw-w64

**Comment by tianjunwork** [comment]
Hi @jsunintel Could you take a look?

**Comment by tianjunwork** [comment]
Hi @1480c1 could you share your command line for both?

**Comment by 1480c1** [comment]
`.\SvtHevcEncApp.exe -i ..\akiyo_cif.yuv -b test.265 -w 352 -h 288 -fps-num 30000 -fps-denom 1001` for Windows based mingw-w64
`/SvtHevcEncApp -i ../akiyo_cif.yuv -b test.265 -w 352 -h 288 -fps-num 30000 -fps-denom 1001` for Ubuntu

`ffprobe -i test.265` for both

**Comment by lijing0010** [comment]
@jsunintel , is it something you fixed recently?

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel , is it something you fixed recently?

This one has nothing to do with FFmpeg plugin. It's all about SVT itself.

**Comment by intelmark** [comment]
Did some debug logging with ffmpeg's ffprobe and noticed that the 25 fps is a default value. 

ffprobe seems to decode each frame and then calculate an fps value.  The function avformat_find_stream_info attempts to read the frames, however the decoded time stamps (dts) on the packets returned from read_frame_internal seem to be invalid.  Subsequently ff_rfps_calculate can not calculate an appropriate fps.

**Comment by tianjunwork** [comment]
Hi @1480c1, use "-fpsinvps 1" will give you the correct fps number with ffprobe.

**Comment by tianjunwork** [comment]
Thx @intelmark for investigating ffmpeg behavior.
