### ISSUE TITLE
SVT HEVC encode failed by multi-tasks.

### ISSUE THREAD

**Issue by jsunintel** [OpenVisualCloud/SVT-HEVC#221]
Run the below command in one console:
./ffmpeg -stream_loop 100 -i /tmp/ramdisk/8k2D_musician_360_h264.mp4 -c:v libsvt_hevc -rc 1 -b:v 13M -g 60 -tune 1 -preset 10 -vframes 4000 -f null -

Then quickly swith to another console, run the same cmdline.

The first one will fail with "killed" information prompted.

The same for SvtHevcEncApp. Running 2 such cmdlines on 2 consoles simutanously caused one of executions got "killed":

./SvtHevcEncApp -w 7680 -h 3840 -encMode 10 -n 4000 -fps-num 60 -fps-denom 1 -i /tmp/ramdisk/8k2D_musician_360.yuv

**Comment by tianjunwork** [comment]
Hi @jsunintel, I can't reproduce on 6140 server. What is your hw env?
![Capture](https://user-images.githubusercontent.com/4551215/59885477-3cf7be00-9370-11e9-8031-2dc480e373ea.JPG)

**Comment by jsunintel** [comment]
It's 8180.

**Comment by tianjunwork** [comment]
Hi @Austin-Hu, do you have Xeon 81xx. Both this issue and #219(cpu utilization drop) can't be reproduced on 6140. Could you be able to try it?

**Comment by tianjunwork** [comment]
Hi @jsunintel, I simulate the extreme mem usage in https://github.com/OpenVisualCloud/SVT-HEVC/issues/219#issuecomment-506476395. Encoders can still run.
Could you either provide more postmortem info or grant me access to your server?

**Comment by jsunintel** [comment]
> 
> 
> Hi @jsunintel, I simulate the extreme mem usage in [#219 (comment)](https://github.com/OpenVisualCloud/SVT-HEVC/issues/219#issuecomment-506476395). Encoders can still run.
> Could you either provide more postmortem info or grant me access to your server?

The diff is probably caused different memory sizes on different machines. You could start more than 2 encoding processes simutanously to trigger the killing event. Please try 4 or 8.

**Comment by tianjunwork** [comment]
@jsunintel As you can see from #219 (comment), running 3x8k encoding with max lookahead, 155G memory out of 156G is used.

**Comment by tianjunwork** [comment]
With two 8k encoding process running, one of them got "Program terminated with signal SIGKILL, Killed. " after a while.
The kernel OOM killer terminated it (effectively the kernel executed kill -9 for it). /var/log/syslog shows:
```Out of memory: Kill process 117802 (SvtHevcEncApp) score 393 or sacrifice child
 Killed process 117802 (SvtHevcEncApp) total-vm:69449144kB, anon-rss:53323628kB, file-rss:0kB, shmem-rss:0kB```
This is a generic issue not related to SVT encoder.
