### ISSUE TITLE
[SVT-HEVC]Parameter "-separate-fields" set to 1 not take effect and generated bitstreams has garbage 

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-HEVC#227]
Tested with master code with commit ID 9ffbf87, try to set parameter "-separate-fields" to 1 and generate the bitstreams, encoder can be successfully finished. But while use Windows tool to check the generated bitstreams, we found there is garbage in video screen and top and bottom fields in one frame are not separated.

Test command we used:
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M0_Fallout4_1920x1080_8bit_60Hz_P420_Q48_SQ_1_1.265 -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 40  -encMode 0  -interlaced-video 1  -compressed-ten-bit-format 0  -rc 0  **-separate-fields 1**  -tbr 7741055  -tune 0  -q 48

This issue is occurred from commit ID 4a38056.

Screen short of generated bitstreams:
![defiled](https://user-images.githubusercontent.com/46477459/60162758-c275e500-982c-11e9-8cdb-770e84791678.png)

**Comment by tianjunwork** [comment]
Hi @liweki, could you check if #233 fix this issue? Thx.

**Comment by tianjunwork** [comment]
BTW, "-interlaced-video 1" and "-separate-fields 1" conflicts.
-separate-fields 1 means the input is interlaced, the encoder process the yuv and encode it as progressive. The output is progressive.
-interlaced-video 1 means the encoder indicates output is interlaced video content. To be specific, refer to http://ramugedia.com/interlace-support-in-hevc.

**Comment by tianjunwork** [comment]
Hi @liweki, could you see if #223 address your issue? Thx.
