### ISSUE TITLE
[SVT-HEVC] OQ between encMode 0&1 has the same quality, and also have the same bitstreams 

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-HEVC#235]
Run test with master code with commit ID 7ef5fc8, found in OQ mode (-tune 1) between encMode 0 and 1, the generated bitstreams have the same quality.
In VMAF mode (-tune 2) between encMode 4 and 5 for resolution 1280x720, 1920x1080, encMode 5 and 6 for 3840x2160, also have the same quality issue.

Test command we used:
**OQ:** 
encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv -b bitstreams/M0_DucksTakeOff_1280x720_8bit_50Hz_P420_Q42_OQ.265 -w 1280 -h 720 -bit-depth 8 -fps 50 -intra-period 47 -n 40 **-encMode 0** -compressed-ten-bit-format 0 -rc 0 -tune 1 -q 42

encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv -b bitstreams/M1_DucksTakeOff_1280x720_8bit_50Hz_P420_Q42_OQ.265 -w 1280 -h 720 -bit-depth 8 -fps 50 -intra-period 47 -n 40 **-encMode 1** -compressed-ten-bit-format 0 -rc 0 -tune 1 -q 42

**VMAF:**
encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv -b bitstreams/M5_DucksTakeOff_1280x720_8bit_50Hz_P420_Q42_VMAF.265 -w 1280 -h 720 -bit-depth 8 -fps 50 -intra-period 47 -n 40 **-encMode 5** -compressed-ten-bit-format 0 -rc 0 -tune 2 -q 42

encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv -b bitstreams/M4_DucksTakeOff_1280x720_8bit_50Hz_P420_Q42_VMAF.265 -w 1280 -h 720 -bit-depth 8 -fps 50 -intra-period 47 -n 40 **-encMode 4** -compressed-ten-bit-format 0 -rc 0 -tune 2 -q 42

**Comment by tianjunwork** [comment]
Hi @liweki, Thanks letting us know the issue. In the coming months, we plan to refactor the encMode logic and tune each setting. 
I wonder if you could provide more feedback between OQ and VMAF? Which one is the preferred mode in your usage?

**Comment by lijing0010** [comment]
@liweki ,could you re-test it with the latest master branch?
Note: we only support tune 1 now, so don't need test for tune 0 and tune 2

**Comment by tianjunwork** [comment]
Verified: "-tune 1" between encMode 0&1 have the same bitstreams.

**Comment by liweki** [comment]
This issue is verified Pass with latest master commit 039366e, so close it.
