### ISSUE TITLE
The speed of encoding one 8Kp60/10-bit streams

### ISSUE THREAD

**Issue by Holly0521** [OpenVisualCloud/SVT-HEVC#237]
I run the commond :
./ffmpeg -i 8k-60fps-10bit-hevc.mkv -c:v libsvt_hevc -tune 0 -preset 11 -rc 1 -b:v 120000k -la_depth 8 -profile:v main10 -tier high -level:v 6.2 -c:a copy -pix_fmt yuv420p10le test-8k.ts
But the speed running in DELL PowerEdge R740 is better than the speed running in DELL PowerEdge R840. Does it need to be added some parameters? Thanks a lot.

**Comment by 1480c1** [comment]
Do you have any specific numbers (fps, etc) and what cpu you have?

**Comment by Holly0521** [comment]
The fps is 19 and the utilization rate of cpu is 3800% running in DELL PowerEdge R740.The fps is 16 and the utilization rate of cpu is 4500% running in DELL PowerEdge R840.
The cpu information of DELL PowerEdge R740 is:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
Stepping:              4
CPU MHz:               2600.000
BogoMIPS:              5200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              19712K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke.
The cpu information of DELL PowerEdge R840 is:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                144
On-line CPU(s) list:   0-143
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz
Stepping:              4
CPU MHz:               2700.000
BogoMIPS:              5406.74
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              25344K
NUMA node0 CPU(s):     0-143

**Comment by Holly0521** [comment]
The cpu model name of DELL PowerEdge R740 is Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz.
The cpu model name of DELL PowerEdge R840 is Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz.

**Comment by tianjunwork** [comment]
Hi @Holly0521, the cpu utilization is pretty low even for R740. Could you run ./SvtHevcEncApp with the same parameters and share the fps and cpu utilization?

**Comment by Holly0521** [comment]
Hi @tianjunwork, I use the commond: 
./SvtHevcEncApp -encMode 12 -tune 0  -color-format 1 -w 7680 -h 4320 -bit-depth 10 -compressed-ten-bit-format 1 -i 8k-10bit.yuv -profile 2  -tier 1 -level 6.2 -rc 1 -tbr 120000000 -fps 60 -n 1800 -b out1.bin
The fps, cpu utilization running in R740 is 15.89fps, 3200%, and in R840 is 26.76fps, 3000%. Thanks a lot.

**Comment by Holly0521** [comment]
Hi @tianjunwork, I use the commond:
./SvtHevcEncApp -encMode 12 -tune 0 -color-format 1 -w 7680 -h 4320 -bit-depth 10 -compressed-ten-bit-format 1 -i 8k-10bit.yuv -profile 2 -tier 1 -level 6.2 -rc 1 -tbr 120000000 -fps 60 -n 1800 -b out1.bin
The fps, cpu utilization running in R740( 2*Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, MemTotal: 125G)  is 26.76fps, 3000%, and in R840(4* Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz, MemTotal: 125G) is 15.89fps, 3200%. The cpu utilization is quite, but why differ greatly in disposition? And the range of parameter TargetSocket is [-1.1], how can I set 3 or 4 if I have 4 sockets? Thanks a lot.

**Comment by Holly0521** [comment]
Hi @tianjunwork, I use the commond:
./SvtHevcEncApp -encMode 12 -tune 0 -color-format 1 -w 7680 -h 4320 -bit-depth 10 -compressed-ten-bit-format 1 -i 8k-10bit.yuv -profile 2 -tier 1 -level 6.2 -rc 1 -tbr 120000000 -fps 60 -n 1800 -b out1.bin
The fps, cpu utilization running in R740( 2*Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, MemTotal: 125G) is 26.76fps, 3000%, and in R840(4*Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz, MemTotal: 125G) is 15.89fps, 3200%. The cpu utilization is equal, but why differ greatly in fps? The range of parameter TargetSocket is [-1.1], and how can I set 3 or 4 if I have 4 sockets? Thanks a lot.

**Comment by tianjunwork** [comment]
For low fps on R840, I suspect the numa effect.
4 socket server is rear on market, the TargetSocket logic is developed for 2 socket server.
You can use numactl -N 0,1 command to run process on node 0,1 for example.
Could you constrain the process on node 0,1 on R840 to see any difference? numactl -N 0,1 ./SvtHevcEncApp ...

**Comment by Holly0521** [comment]
Hi @tianjunwork, I use the commond: numactl --hardware.
R840 (low fps) has 1 node, so it shouldn't have  numa effect.
R740 (high fps) has 2 nodes.

**Comment by tianjunwork** [comment]
Oh, I didn't notice the numa node number. Usually it is the same as socket number. Let me see if I can get the same hw to debug.

**Comment by tianjunwork** [comment]
We don't have similar server internally to debug this issue. If you can use vtune. Could you use numactl -N 0,1 to constrain encoder process within 2 sockets on R840 to see any difference?

**Comment by Holly0521** [comment]
Hi @tianjunwork, thanks for your reply. Then, I'll try it.

**Comment by lijing0010** [comment]
@Holly0521 , could you add -nb 500 with the svt_app and have a try?
The IO of hard-disk is usually a bottleneck

**Comment by Holly0521** [comment]
@lijing0010, thanks for your reply. I have been tried it. And the speed in R840 is faster than before, but the speed in R840 is slower than R740. After I added the number of memory chips, the speed in R840 is faster than in R740.

**Comment by lijing0010** [comment]
@Holly0521 , for fast mode(especially with big resolutions), it's usually memory bounded(not size, but bandwidth). So you need to use more memory channels

**Comment by Holly0521** [comment]
@lijing0010, thanks for your reply. I will add the number of memory chips as many as possible and see the difference.

**Comment by tianjunwork** [comment]
Hi @Holly0521, any BKM to share with the community with your experiment😄? Do you need further help on this issue?

**Comment by Holly0521** [comment]
Hi @tianjunwork, The speed  is faster after adding memory chips than before. And then all my problem would be over.  Could you close this issue? Thanks a lot.
