### ISSUE TITLE
How to control bitrate?

### ISSUE THREAD

**Issue by liudongbo** [OpenVisualCloud/SVT-HEVC#254]
I set some paraments like -rc 1 -tbr 5000,it is not work,help me please

**Comment by intelmark** [comment]
Hi liudongbo!

Hopefully we can help.  Can you provide the full command line you are using and what is making you think that it's not working?

Also refer to the user guide for information about rc1 and setting lookahead distance:
[](https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/Docs/svt-hevc_encoder_user_guide.md)

thanks...
-mark

**Comment by liudongbo** [comment]
Command as follow:
SvtHevcEncApp -i input.yuv -w 1920 -h 1080 -b /output.h265 -rc 1 -tbr 5000

**Comment by intelmark** [comment]
Can you share the output of the encoder and any information about the input.yuv file?

**Comment by liudongbo** [comment]
input.yuv  123 frames and 1920x1080
How can i send output file and input.yuv to you?
Can you give me your e-mail?
thx

**Comment by tianjunwork** [comment]
@liudongbo, -tbr is "Target bitrate in bits / second", 5000 is too low for 1080p. Pls set a higher value. Should fix your issue.

**Comment by liudongbo** [comment]
> @liudongbo, -tbr is "Target bitrate in bits / second", 5000 is too low for 1080p. Pls set a higher value. Should fix your issue.

thank you very much!

**Comment by tianjunwork** [comment]
@liudongbo np, pls let us know if you get it working.

**Comment by liudongbo** [comment]
Target bitrate = -tbr <int>/1000
it working.
