### ISSUE TITLE
when to support building both static/dynamic libs

### ISSUE THREAD

**Issue by andrewmabc** [OpenVisualCloud/SVT-HEVC#255]
when to support building both static/dynamic libs?

**Comment by 1480c1** [comment]
Do you mean building both .a and .so in the same build?

**Comment by tianjunwork** [comment]
Hi @andrewmabc , you can refer to #128. I provided patch you build static libs.

**Comment by andrewmabc** [comment]
I follow the thread's instructions, and use the latest source code. But I fail to link. Below is error message:

[ 87%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbNeighborArrays.c.o
[ 88%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbPictureOperators.c.o
[ 89%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbPredictionStructure.c.o
[ 90%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbProductCodingLoop.c.o
[ 90%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbRateControlTables.c.o
[ 91%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbRateDistortionCost.c.o
[ 92%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbSampleAdaptiveOffsetGenerationDecision.c.o
[ 93%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbSei.c.o
[ 93%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbTransforms.c.o
[ 94%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbTransQuantBuffers.c.o
[ 95%] Building C object Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/EbUtility.c.o
Linking C static library ../../../../Bin/Release/libSvtHevcEnc.a
Error running link command: No such file or directory
Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/build.make:1968: recipe for target '../Bin/Release/libSvtHevcEnc.a' failed
make[2]: *** [../Bin/Release/libSvtHevcEnc.a] Error 2
CMakeFiles/Makefile2:362: recipe for target 'Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/all' failed
make[1]: *** [Source/Lib/Codec/CMakeFiles/SvtHevcEnc.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

I don't know how to change cmake file very well. How to fix the probelm? Thanks!

**Comment by tianjunwork** [comment]
Hi @andrewmabc , if possible, could you attach your patch?

**Comment by andrewmabc** [comment]
below is my patch:

[root]# git diff Source/App/CMakeLists.txt
diff --git a/Source/App/CMakeLists.txt b/Source/App/CMakeLists.txt
old mode 100644
new mode 100755
index b57121c..46b82d0
--- a/Source/App/CMakeLists.txt
+++ b/Source/App/CMakeLists.txt
@@ -13,7 +13,6 @@ include_directories(${PROJECT_SOURCE_DIR}/Source/API/
 add_executable(SvtHevcEncApp
     EbAppConfig.c
     EbAppContext.c
-    EbAppFifo.c
     EbAppMain.c
     EbAppProcessCmd.c
     EbTime.c
@@ -38,5 +37,3 @@ if(UNIX)
             rt)
     endif()
 endif()
-
-install(TARGETS SvtHevcEncApp RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})


[root]# git diff Source/App/EbAppContext.c
diff --git a/Source/App/EbAppContext.c b/Source/App/EbAppContext.c
old mode 100644
new mode 100755
index 421ea78..90f5449
--- a/Source/App/EbAppContext.c
+++ b/Source/App/EbAppContext.c
@@ -260,7 +260,7 @@ EB_ERRORTYPE CopyConfigurationParameters(
 }
 
 
-EB_ERRORTYPE AllocateFrameBuffer(
+static EB_ERRORTYPE AllocateFrameBuffer(
     EbConfig_t          *config,
     uint8_t               *pBuffer)
 {


[root]# git diff Source/App/EbTime.c
diff --git a/Source/App/EbTime.c b/Source/App/EbTime.c
old mode 100644
new mode 100755
index 61c91cb..4220dbf
--- a/Source/App/EbTime.c
+++ b/Source/App/EbTime.c
@@ -22,7 +22,7 @@
 #error OS/Platform not supported.
 #endif
 
-void EbStartTime(
+static void EbStartTime(
     uint64_t *Startseconds,
     uint64_t *Startuseconds)
 {
@@ -42,7 +42,7 @@ void EbStartTime(
 
 }
 
-void EbFinishTime(
+static void EbFinishTime(
     uint64_t *Finishseconds,
     uint64_t *Finishuseconds)
 {
@@ -61,7 +61,7 @@ void EbFinishTime(
 #endif
 
 }
-void EbComputeOverallElapsedTime(
+static void EbComputeOverallElapsedTime(
     uint64_t Startseconds,
     uint64_t Startuseconds,
     uint64_t Finishseconds,


[root]# git diff Source/Lib/Codec/CMakeLists.txt
diff --git a/Source/Lib/Codec/CMakeLists.txt b/Source/Lib/Codec/CMakeLists.txt
old mode 100644
new mode 100755
index fbffdd9..4105d02
--- a/Source/Lib/Codec/CMakeLists.txt
+++ b/Source/Lib/Codec/CMakeLists.txt
@@ -19,7 +19,7 @@ link_directories(${PROJECT_SOURCE_DIR}/Source/Lib/ASM_SSE2/
     ${PROJECT_SOURCE_DIR}/Source/Lib/ASM_AVX2/)
 
 # Encoder Lib Source Files
-add_library(SvtHevcEnc SHARED
+add_library(SvtHevcEnc
     EbAdaptiveMotionVectorPrediction.h
     EbAvailability.h
     EbAvcStyleMcp.h

**Comment by andrewmabc** [comment]
[root]# git diff Source/App/CMakeLists.txt
diff --git a/Source/App/CMakeLists.txt b/Source/App/CMakeLists.txt
old mode 100644
new mode 100755
index b57121c..46b82d0
--- a/Source/App/CMakeLists.txt
+++ b/Source/App/CMakeLists.txt
@@ -13,7 +13,6 @@ include_directories(${PROJECT_SOURCE_DIR}/Source/API/
 add_executable(SvtHevcEncApp
     EbAppConfig.c
     EbAppContext.c
-    EbAppFifo.c
     EbAppMain.c
     EbAppProcessCmd.c
     EbTime.c
@@ -38,5 +37,3 @@ if(UNIX)
             rt)
     endif()
 endif()
-
-install(TARGETS SvtHevcEncApp RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})

[root]# git diff Source/App/EbAppContext.c
diff --git a/Source/App/EbAppContext.c b/Source/App/EbAppContext.c
old mode 100644
new mode 100755
index 421ea78..90f5449
--- a/Source/App/EbAppContext.c
+++ b/Source/App/EbAppContext.c
@@ -260,7 +260,7 @@ EB_ERRORTYPE CopyConfigurationParameters(
 }
 
 
-EB_ERRORTYPE AllocateFrameBuffer(
+static EB_ERRORTYPE AllocateFrameBuffer(
     EbConfig_t          *config,
     uint8_t               *pBuffer)
 {

[root]# git diff Source/App/EbTime.c
diff --git a/Source/App/EbTime.c b/Source/App/EbTime.c
old mode 100644
new mode 100755
index 61c91cb..4220dbf
--- a/Source/App/EbTime.c
+++ b/Source/App/EbTime.c
@@ -22,7 +22,7 @@
 #error OS/Platform not supported.
 #endif
 
-void EbStartTime(
+static void EbStartTime(
     uint64_t *Startseconds,
     uint64_t *Startuseconds)
 {
@@ -42,7 +42,7 @@ void EbStartTime(
 
 }
 
-void EbFinishTime(
+static void EbFinishTime(
     uint64_t *Finishseconds,
     uint64_t *Finishuseconds)
 {
@@ -61,7 +61,7 @@ void EbFinishTime(
 #endif
 
 }
-void EbComputeOverallElapsedTime(
+static void EbComputeOverallElapsedTime(
     uint64_t Startseconds,
     uint64_t Startuseconds,
     uint64_t Finishseconds,

[root]# git diff Source/Lib/Codec/CMakeLists.txt
diff --git a/Source/Lib/Codec/CMakeLists.txt b/Source/Lib/Codec/CMakeLists.txt
old mode 100644
new mode 100755
index fbffdd9..4105d02
--- a/Source/Lib/Codec/CMakeLists.txt
+++ b/Source/Lib/Codec/CMakeLists.txt
@@ -19,7 +19,7 @@ link_directories(${PROJECT_SOURCE_DIR}/Source/Lib/ASM_SSE2/
     ${PROJECT_SOURCE_DIR}/Source/Lib/ASM_AVX2/)
 
 # Encoder Lib Source Files
-add_library(SvtHevcEnc SHARED
+add_library(SvtHevcEnc
     EbAdaptiveMotionVectorPrediction.h
     EbAvailability.h
     EbAvcStyleMcp.h

**Comment by andrewmabc** [comment]
[svt-hevc_patch.txt](https://github.com/OpenVisualCloud/SVT-HEVC/files/3422308/svt-hevc_patch.txt)
this is the patch

**Comment by tianjunwork** [comment]
Hi @1480c1, would you like to try out the patch and help @andrewmabc out? Thanks:)

**Comment by 1480c1** [comment]
Sure, I can try to figure out. I primarily would like to add static libs support like SVT-AV1 did, but the main problem is duplication in time functions from lib and app and some others

**Comment by tianjunwork** [comment]
Hi @1480c1, any update?

**Comment by 1480c1** [comment]
Still trying, but still getting errors with not found symbols for DSO

**Comment by 1480c1** [comment]
Since SVT-AV1 and SVT-HEVC have different file layouts+code layouts, I can't simulate the same changes as was done there

**Comment by tianjunwork** [comment]
Could you share what you had done and we work together on it?

**Comment by 1480c1** [comment]
I have tried renaming the conflicting functions in the app folder to prefix with App and that worked when compiling with a static lib, however, it failed when I tried to compile with a shared lib.

I've tried deduplicating the functions from the app folder and keeping the ones in the codec folder, but that resulted in the DSO errors.

Going to try to see if I can replicate the errors again

**Comment by 1480c1** [comment]
@jsunintel, is EbTime.h necessary in the ffmpeg patch? Looking at both the one in the repo and the one submitted to ffmpeg, I do not see anything mentioned in the header present in the patches

**Comment by tianjunwork** [comment]
Both EbTime.h and EbErrorCodes.h are not needed. Ffmpeg can be built without them.

**Comment by 1480c1** [comment]
How about for gstreamer?

**Comment by tianjunwork** [comment]
only EbApi.h is used in gst.

**Comment by 1480c1** [comment]
maybe we should add a test if the gstreamer patch will apply since I can't seem to apply the gstreamer patch according to the README

**Comment by tianjunwork** [comment]
You mean ffmpeg patch? gst plugin is not patch.
```
 --- /dev/null
 +++ b/libavcodec/libsvt_hevc.c
-@@ -0,0 +1,501 @@
+@@ -0,0 +1,499 @@
 +/*
 +* Scalable Video Technology for HEVC encoder library plugin
 +*
@@ -103,8 +103,6 @@ index 0000000..d9ac04c
 +* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 +*/
 +
-+#include "EbErrorCodes.h"
-+#include "EbTime.h"
 +#include "EbApi.h"
```

**Comment by 1480c1** [comment]
No, I mean the git-patch

**Comment by 1480c1** [comment]
Or is the git-patch not actually needed at all?

**Comment by 1480c1** [comment]
I do notice that the commit message for the patch in #157 notes it's for gstreamer 1.17.0

**Comment by tianjunwork** [comment]
The git-patch is a different solution that applies to gst code base. We shall keep both.
When you modify the patch file, besides the lines you would like to remove, also reduce the number of new code.
Refer to above ffmpeg patch.

**Comment by 1480c1** [comment]
I see, I've temporarily rebased the patches for now, will remove the extra lines now

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel, is EbTime.h necessary in the ffmpeg patch? Looking at both the one in the repo and the one submitted to ffmpeg, I do not see anything mentioned in the header present in the patches

They are included but not used for now.

**Comment by 1480c1** [comment]
> > @jsunintel, is EbTime.h necessary in the ffmpeg patch? Looking at both the one in the repo and the one submitted to ffmpeg, I do not see anything mentioned in the header present in the patches
> 
> They are included but not used for now.

Do you mind if I remove them? I'm trying to https://github.com/OpenVisualCloud/SVT-AV1/pull/67 by deduplicating the functions

Also, I personally would prefer that the compiler and preprocessor doesn't have to process code not present. Plus if the code is necessary, they can be implemented at a later time.

**Comment by jsunintel** [comment]
> 
> 
> > > @jsunintel, is EbTime.h necessary in the ffmpeg patch? Looking at both the one in the repo and the one submitted to ffmpeg, I do not see anything mentioned in the header present in the patches
> > 
> > 
> > They are included but not used for now.
> 
> Do you mind if I remove them? I'm trying to [OpenVisualCloud/SVT-AV1#67](https://github.com/OpenVisualCloud/SVT-AV1/pull/67) by deduplicating the functions
> 
> Also, I personally would prefer that the compiler and preprocessor doesn't have to process code not present. Plus if the code is necessary, they can be implemented at a later time.

It's OK.
