### ISSUE TITLE
10-bit source problem

### ISSUE THREAD

**Issue by calvinckfong** [OpenVisualCloud/SVT-HEVC#259]
I create a 10-bit source using gstreamer:
`gst-launch-1.0 -v videotestsrc num-buffers=300 ! video/x-raw,width=640,height=480,format=I420_10LE,colorimetry=bt2020 ! filesink location=test10Bit.yuv`

Then I encode the yuv file with the following command:
`./SvtHevcEncApp -i test10bit.yuv -w 640 -h 480 -fps 30 -rc 1 -tbr 2000000 -scd 1 -intra-period 29 -bit-depth 10 -compressed-ten-bit-format 0 -b test10bit.hevc`

Unfortunately, the coded video is corrupted:
![test10bit hevc_snapshot](https://user-images.githubusercontent.com/16603747/61451104-3bc7aa00-a98b-11e9-91bc-b73a0e01414c.png)

I would like to know if it is bug when coding with 10-bit source or I did something wrong.
Thanks.

**Comment by tianjunwork** [comment]
Hi @calvinckfong, I use the same command line, could not reproduce the issue.
I notice that you generated **test10Bit.yuv**, but encode **test10bit.yuv**. Do you have test10bit.yuv that is a different color format?

**Comment by calvinckfong** [comment]
Thank you for your quick response.
Sorry for typo in the yuv filename.  I made sure that the file is generated from that gstreamer command.
I guess I figure out the reason.  I retried the encoding command with **-asm 0** option and the output becomes artifact-free.  My machine's CPU is i7-7700 support up to AVX2.  Possibly the bug only appears in AVX2 or below optimization.  Would you mind to take a look?  At the same time, I will arrange another machine with AVX-512 for testing.  I will share my findings later.

Thanks.

**Comment by calvinckfong** [comment]
Those command are run on machine with Xeon(R) Gold 6136.  The result is artifact-free.

**Comment by tianjunwork** [comment]
Hi @calvinckfong, thanks for doing the experiments which helps root cause.

**Comment by calvinckfong** [comment]
Welcomed.  If any further information is needed, please let me know.

**Comment by calvinckfong** [comment]
@Austin-Hu, Noted! Thanks a lot.
