### ISSUE TITLE
Core dump issue with high resolution input

### ISSUE THREAD

**Issue by Stephanie-Qi** [OpenVisualCloud/SVT-HEVC#260]
I encode 8k yuv input with following command line:
./SvtHevcEncApp -i 8k.yuv -w 7680 -h 3840 -scd 0 -tune 0 -intra-period 14 -lad 14 -rc 1 -tbr 100000000 -hierarchical-levels 3 -pred-struct 2 -base-layer-switch-mode 1 -fps-num 30000 -fps-denom 1001 -n 2000 -b test.265

After ~300 frames encoded, core dump issue happened. I have tried several times, core dump issue arises every time. 

And this issue disappeared with 4k input.

**Comment by tianjunwork** [comment]
Hi @Stephanie-Qi Thx reporting the issue. Could you verity if #261 address your issue?

**Comment by Stephanie-Qi** [comment]
> Hi @Stephanie-Qi Thx reporting the issue. Could you verity if #261 address your issue?

Yes, seems it fixed my issue. Thank you!
