### ISSUE TITLE
[SVT-HEVC]If setting parameter -sao 1 or -dlf 1, the encoded output bitstreams have run to run issue with YUV420/422/444 input clip

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-HEVC#276]
**[Test environment]**
OS： Ubuntu 18.04.2 LTS
Master Commit ID: 94996f6

**[Issue Description]**
While use SVT-HEVC master code with Commit ID 94996f6 to run the same command line for many times (about 10 times) with Parameter -sao 1 or -dlf 1 setting, found the encoded bitstreams have run to run issue (different file size and md5 value).

The issue is reproducible with YUV420/422/444 input clips.
The detail test data and command line we used as following:
**YUV422:**
- encoders/SvtHevcEncApp -encMode 10 -w 3840 -h 2160 -i yuvs/Netflix_Crosswalk_3840x2160_10bit_60Hz_P422.yuv -q 27 -fps 60 -b 242/3840x2160_10bit_60Hz_P422_Q27-M10-SAO-1_1.bin -n 200 -intra-period 63 -bit-depth 10 -lad 63 -hdr 0 -tune 1 **-sao 1** -color-format 2
-rw-rw-r-- 1 media media 3944593 7月  24 00:13 242/3840x2160_10bit_60Hz_P422_Q27-M10-SAO-1_1.bin
-rw-rw-r-- 1 media media 3944593 7月  24 00:12 242/3840x2160_10bit_60Hz_P422_Q27-M10-SAO-1_2.bin
-rw-rw-r-- 1 media media 3944593 7月  24 00:12 242/3840x2160_10bit_60Hz_P422_Q27-M10-SAO-1_3.bin
-rw-rw-r-- 1 media media **3944644** 7月  24 00:12 242/3840x2160_10bit_60Hz_P422_Q27-M10-SAO-1_4.bin

- encoders/SvtHevcEncApp -encMode 10 -w 3840 -h 2160 -i yuvs/Netflix_Crosswalk_3840x2160_10bit_60Hz_P422.yuv -q 27 -fps 60 -b 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-1.bin -n 200 -intra-period 63 -bit-depth 10 -lad 63 -hdr 0 -tune 1 **-dlf 1** -color-format 2
-rw-rw-r-- 1 media media 3968772 7月  23 23:00 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-1.bin
-rw-rw-r-- 1 media media 3968772 7月  23 23:00 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-2.bin
-rw-rw-r-- 1 media media 3968772 7月  23 23:01 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-3.bin
-rw-rw-r-- 1 media media **3969068** 7月  23 23:02 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-4.bin
-rw-rw-r-- 1 media media 3968772 7月  23 23:02 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-5.bin
-rw-rw-r-- 1 media media 3968772 7月  23 23:03 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-6.bin
-rw-rw-r-- 1 media media **3969247** 7月  23 23:10 242/3840x2160_10bit_60Hz_P422_Q27-M10-dlf-1-no-nb-7.bin

**YUV420:**
- encoders/SvtHevcEncApp -encMode 10 -w 3840 -h 2160 -i yuvs/Netflix_Crosswalk_3840x2160_10bit_60Hz_P420.yuv -q 27 -fps 60 -b 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-9.bin -n 200 -intra-period 63 -bit-depth 10 -lad 63 -hdr 0 -tune 1  -color-format 1 **-dlf 1**
ll 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-*
-rw-rw-r-- 1 media media 3486089 7月  24 01:06 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-1.bin
-rw-rw-r-- 1 media media 3486089 7月  24 01:06 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-2.bin
-rw-rw-r-- 1 media media 3486089 7月  24 01:07 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-3.bin
-rw-rw-r-- 1 media media 3486089 7月  24 01:07 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-4.bin
-rw-rw-r-- 1 media media 3486089 7月  24 01:07 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-5.bin
-rw-rw-r-- 1 media media **3486221** 7月  24 01:08 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-6.bin
-rw-rw-r-- 1 media media 3486089 7月  24 01:09 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-7.bin
-rw-rw-r-- 1 media media **3485802** 7月  24 01:10 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-8.bin
-rw-rw-r-- 1 media media **3485670** 7月  24 01:10 242/3840x2160_10bit_60Hz_P420_Q27-M10_dlf-1-no-nb-9.bin

**YUV444:**
- encoders/SvtHevcEncApp -encMode 10 -w 3840 -h 2160 -i yuvs/Netflix_Crosswalk_3840x2160_10bit_60Hz_P444.yuv -q 27 -fps 60 -b 242/3840x2160_10bit_60Hz_P444_Q27-M10_dlf-1-no-nb-5.bin -n 200 -intra-period 63 -bit-depth 10 -lad 63 -hdr 0 -tune 1  -color-format 3 **-dlf 1**
ll 242/3840x2160_10bit_60Hz_P444_Q27-M10_dlf-1-no-nb-*
-rw-rw-r-- 1 media media 4328375 7月  24 01:13 242/3840x2160_10bit_60Hz_P444_Q27-M10_dlf-1-no-nb-1.bin
-rw-rw-r-- 1 media media 4328375 7月  24 01:14 242/3840x2160_10bit_60Hz_P444_Q27-M10_dlf-1-no-nb-2.bin
-rw-rw-r-- 1 media media **4328271** 7月  24 01:14 242/3840x2160_10bit_60Hz_P444_Q27-M10_dlf-1-no-nb-3.bin
-rw-rw-r-- 1 media media 4328375 7月  24 01:15 242/3840x2160_10bit_60Hz_P444_Q27-M10_dlf-1-no-nb-4.bin
-rw-rw-r-- 1 media media 4328375 7月  24 01:15 242/3840x2160_10bit_60Hz_P444_Q27-M10_dlf-1-no-nb-5.bin

- encoders/SvtHevcEncApp -encMode 10 -w 3840 -h 2160 -i yuvs/Netflix_Crosswalk_3840x2160_10bit_60Hz_P444.yuv -q 27 -fps 60 -b 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-12.bin -n 200 -intra-period 63 -bit-depth 10 -lad 63 -hdr 0 -tune 1  -color-format 3 **-sao 1**
ll 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-*
-rw-rw-r-- 1 media media 4303053 7月  24 01:23 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-10.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:24 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-11.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:24 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-12.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:17 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-1.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:18 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-2.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:19 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-3.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:20 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-4.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:20 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-5.bin
-rw-rw-r-- 1 media media 4303035 7月  24 01:21 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-6.bin
-rw-rw-r-- 1 media media 4303035 7月  24 01:21 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-7.bin
-rw-rw-r-- 1 media media 4303053 7月  24 01:22 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-8.bin
-rw-rw-r-- 1 media media **4303128** 7月  24 01:23 242/3840x2160_10bit_60Hz_P444_Q27-M10_sao-1-no-nb-9.bin

BTW, I try to use above command line to encode 40 frames and run it for 20 times, not see r2r issue.

**Comment by lijing0010** [comment]
@liweki , could you use the latest master to verify this? I tried   your command for more than 20 times, didn't reproduce it

**Comment by wangjingz** [comment]
can't reproduce with the Master --short HEAD 5107c84

**Comment by tianjunwork** [comment]
Thanks all helping on this issue.
