### ISSUE TITLE
[SVT-HEVC]Some test found the md5 value of encoded stream is differ but have same bitstream size between AsmType enable and disable.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-HEVC#281]
[Test environment]
OS: Ubuntu 18.04.2 LTS
SVT CommitID: 1a9474a

[Issue Description]
During run SVT-HEVC test with Commit ID 1a9474a, found the md5 value of the encoded streams is different between AsmType enable and disable when encoding with some special combination of encoding parameters.
For example:
1920x1080_P422 input, encMode 0, qp 41
1920x1080_P444 input, encMode 4, qp 33
7680x3840_P420 input, encMode 6, qp 35

Test command line we used:
encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/Fallout4_1920x1080_8bit_60Hz_P422.yuv  -b asm_test_M0_Fallout4_1920x1080_8bit_60Hz_P422_Q41_OQ_0.265 -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -encMode 0  -tune 1  -asm 0  -compressed-ten-bit-format 0  -q 41  -color-format 2  -rc 0 
encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/Fallout4_1920x1080_8bit_60Hz_P422.yuv  -b asm_test_M0_Fallout4_1920x1080_8bit_60Hz_P422_Q41_OQ_1.265 -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -encMode 0  -tune 1  -asm 1  -compressed-ten-bit-format 0  -q 41  -color-format 2  -rc 0

encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/Fallout4_1920x1080_8bit_60Hz_P444.yuv  -b asm_test_M4_Fallout4_1920x1080_8bit_60Hz_P444_Q33_OQ_0.265 -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -encMode 4  -tune 1  -asm 0  -compressed-ten-bit-format 0  -q 33  -color-format 3  -rc 0 
encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/Fallout4_1920x1080_8bit_60Hz_P444.yuv  -b asm_test_M4_Fallout4_1920x1080_8bit_60Hz_P444_Q33_OQ_1.265 -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -encMode 4  -tune 1  -asm 1  -compressed-ten-bit-format 0  -q 33  -color-format 3  -rc 0

encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/8k2D_musician_7680x3840_8bit_30Hz_P420.yuv  -b asm_test_M6_8k2D_musician_7680x3840_8bit_30Hz_P420_Q35_OQ_0.265  -w 7680  -h 3840  -bit-depth 8  -fps 30  -intra-period 23  -n 20  -encMode 6  -tune 1  -asm 0  -compressed-ten-bit-format 0  -q 35  -color-format 1  -rc 0
encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/8k2D_musician_7680x3840_8bit_30Hz_P420.yuv  -b asm_test_M6_8k2D_musician_7680x3840_8bit_30Hz_P420_Q35_OQ_1.265   -w 7680  -h 3840  -bit-depth 8  -fps 30  -intra-period 23  -n 20  -encMode 6  -tune 1  -asm 1  -compressed-ten-bit-format 0  -q 35  -color-format 1  -rc 0
![P422](https://user-images.githubusercontent.com/45022980/61928623-a12f2280-afab-11e9-8617-922d58b54d32.png)
![p444](https://user-images.githubusercontent.com/45022980/61928624-a1c7b900-afab-11e9-96cd-0d67b8cb383b.png)

**Comment by Austin-Hu** [comment]
Fixed the issue with PR #[292](https://github.com/OpenVisualCloud/SVT-HEVC/pull/292).

@lijing0010 @tianjunwork , please help review the PR and add Hassene/Kelvin as the reviewer. Thanks!

**Comment by Austin-Hu** [comment]
Verified that all the 3 reported cases (YUV 420/422/444) were fixed by PR #[292](https://github.com/OpenVisualCloud/SVT-HEVC/pull/292).
