### ISSUE TITLE
[FFmpeg plugin] Code typo in ffmpeg patch

### ISSUE THREAD

**Issue by jas0n1ee** [OpenVisualCloud/SVT-HEVC#285]
https://github.com/OpenVisualCloud/SVT-HEVC/blob/9c4a8d8e52e5c41fccd557492f2e074cd7818b8f/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L576

This line should config the availability of `YUV422P10`, instead, it's `YUV420P10`.

**Comment by tianjunwork** [comment]
@jas0n1ee Thanks for submitting the issue.
Hi @jsunintel could you fix it? Thx.

**Comment by luigi311** [comment]
I went ahead and made the change since it was a simple fix and submitted the pull request

**Comment by jsunintel** [comment]
> 
> 
> @jas0n1ee Thanks for submitting the issue.
> Hi @jsunintel could you fix it? Thx.

It's a patch, but not an issue. The patch looks all right to me.
