### ISSUE TITLE
Support CBR rate control mode

### ISSUE THREAD

**Issue by tskomudek** [OpenVisualCloud/SVT-HEVC#298]
Hi,
are there any plans to support a CBR mode or a pluggable BRC module ?
Thx

**Comment by lijing0010** [comment]
Already have a HRD compliance CBR.
See parameters like "-hrd" and "vbv-xxx"

For pluggable BRC, you can modify in InitialRateControlKernel and RateControlKernel(You may refer to SVT-AV1 if you want to integrate your BRC, we had 2 brc there). 

Just keep in mind that SVT is a highly paralleled encoder, so frames coming to BRC module are out-of-order(not decoder order, not display order either)

**Comment by tskomudek** [comment]
Great, i will check this out. Thx
