### ISSUE TITLE
Cannot encode to 10bit garbage output

### ISSUE THREAD

**Issue by thx4ever** [OpenVisualCloud/SVT-HEVC#309]
Hi, i tryed to encode a 8bit yuv to 10bit HEVC bitstream and it output a green screen garbage, could u take a look for me?
Here is the command line options i'm using

SvtHevcEncApp -i D:\8bit.yuv -n 0 -w 1920 -h 1080 -b C:\Users\thx4ever\Desktop\10bit.hevc -intra-period 239 -rc 1 -encMode 3 -bit-depth 10 -profile 2 -fps-num 24000 -fps-denom 1001 -hierarchical-levels 3 -search-w 256 -search-h 256 -tbr 4950000 -vbv-maxrate 20000000 -lad 100 -fpsinvps 1 -ua-delm 1
For 8bit encoding are fine but 10 bit final result are garbage
I'm using version 1.4 from git
My PC Specs
Intel i7 7700
Windows 10 Pro x64

Regards

[10bit_garbage_out.zip](https://github.com/OpenVisualCloud/SVT-HEVC/files/3488519/10bit_garbage_out.zip)

**Comment by intelmark** [comment]
Are you able to share 8bit.yuv?

**Comment by tianjunwork** [comment]
Hi, @thx4ever, -bit-depth specifies the bit depth of input video. SVT encoder can't convert 8bit to 10bit input. With this command line, garbage output is a sure thing.
What behavior that you expect from svt encoder?

**Comment by thx4ever** [comment]
Thanks i was thinkg the software will upconvert to 10 bit
Thanks
