### ISSUE TITLE
Error Mingw: Replace some more _MSC_VER with _WIN32 (#311)

### ISSUE THREAD

**Issue by Jamaika1** [OpenVisualCloud/SVT-HEVC#317]
In file included from c:\msys911\lib\gcc\x86_64-w64-mingw32\9.1.1\include\immintrin.h:43,
                 from EbDefinitions.h:234,
                 from EbEncHandle.c:17:
EbEncHandle.c: In function 'CheckXcr0Ymm':
c:\msys911\lib\gcc\x86_64-w64-mingw32\9.1.1\include\xsaveintrin.h:60:1: error: inlining failed in call to always_inline '_xgetbv': target specific option mismatch
   60 | _xgetbv (unsigned int __A)
      | ^~~~~~~
EbEncHandle.c:516:22: note: called from here
  516 |     xcr0 = (uint32_t)_xgetbv(0);  /* min VS2010 SP1 compiler is required */

**Comment by 1480c1** [comment]
Can you provide your cmake commands/other commands and how did you get your mingw-w64 toolchain?

_Originally posted by @1480c1 in https://github.com/OpenVisualCloud/SVT-HEVC/pull/311#issuecomment-521520834_

**Comment by tianjunwork** [comment]
No replay for too long. Close the issue.
