### ISSUE TITLE
ffmpeg with libsvt_hevc fail to output video with specified resolution

### ISSUE THREAD

**Issue by andrewmabc** [OpenVisualCloud/SVT-HEVC#319]
I build ffmpeg with svt hevc using ffmpeg plugin patch. The following command outputs video with 960x544 instead of 960x540:

ffmpeg -c:v hevc -i h265_resolution_3840x2160_frame_rate_25_bitrate_34836000.mp4 -b:a 48000 -ar 44100 -g 250 -bufsize:v 1555200 -preset 9 -c:a libfdk_aac -c:v libsvt_hevc -maxrate:v 2073600 -profile:v 1 -vf "scale=w=960:h=540" -b:v 1036800 -movflags +faststart -strict -3 -vsync passthrough -f mp4 output.mp4

is it a bug?

Thanks!

**Comment by tianjunwork** [comment]
Hi @jsunintel, could you help take a look? Thank you.

**Comment by jsunintel** [comment]
540 is not a multiple of 8. SVT HEVC lib automatically changes it to 544. I don't think that's a bug.

**Comment by tianjunwork** [comment]
540 is padded to 544. The new size and crop windows info is written to SPS.
![crop](https://user-images.githubusercontent.com/4551215/63289392-d9a4e200-c273-11e9-9962-c8a875210efd.PNG)
To understand stride:
https://docs.microsoft.com/en-us/windows/win32/medfound/image-stride

**Comment by tianjunwork** [comment]
Padding is allowed for encoding. Not a SVT issue. Close.

**Comment by jsunintel** [comment]
Hi Jing,
After solved last issue, we built trust with JD engineers. Today they reported another issues which he already submitted on github (https://github.com/OpenVisualCloud/SVT-HEVC/issues/319 ) and got response, but he didn’t satisfy. Do you have further explanation or work around solution to solve this kind of resolution issues? Thanks! 

Thanks and Best Regards
Xingyi Sun
Software Apps Engineer
IAGS CPDP CEE Cloud Software Engineering
Intel Corporation

**Comment by lijing0010** [comment]
TianJun already explained it above.
From the spec:
"pic_width_in_luma_samples specifies the width of each decoded picture in units of luma samples.
pic_width_in_luma_samples shall not be equal to 0 and shall be an integer multiple of MinCbSizeY.
pic_height_in_luma_samples specifies the height of each decoded picture in units of luma samples.
pic_height_in_luma_samples shall not be equal to 0 and shall be an integer multiple of MinCbSizeY."

So pic_height_in_luma_samples/pic_width_in_luma_samples are multple of MinCbSizeY(which is 8)
and conf_win_xxx_offset is used for the case of non multiple-8 case

**Comment by jsunintel** [comment]
Although 540 is not supported in encoding directly, it is padded to 544, and by setting cropping info in SPS, it is supported.
The EbH265EncStreamHeader has an issue and misses the cropping issue. Corrected it in https://github.com/OpenVisualCloud/SVT-HEVC/pull/394.
