### ISSUE TITLE
x265: SVT-HEVC is not found when building x265 with svt-hevc support

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-HEVC#322]
x265's find module is bound to 1.3.0 and only searches for shared library extensions

https://bitbucket.org/multicoreware/x265/issues/509/x265-fails-to-build-with-current-svt-hevc

**Comment by 1480c1** [comment]
Also, when building ffmpeg with x265 linked with svt-hevc, configure will fail due to undef reference to `EbInitHandle` etc

**Comment by tianjunwork** [comment]
Thanks reporting the issue.

**Comment by 1480c1** [comment]
Also
```
CMake Error at cmake_install.cmake:52 (file):
  file INSTALL cannot find
  "D:/media-autobuild_suite/local64/include/svt-hevc/EbTime.h".


FAILED: CMakeFiles/install.util 
```

**Comment by tianjunwork** [comment]
MCW started working on it. Close this issue.
