### ISSUE TITLE
Regression of PR #264 for windows debug build

### ISSUE THREAD

**Issue by tianjunwork** [OpenVisualCloud/SVT-HEVC#331]
Windows debug build is crashing since #264. Release build is ok.

**Comment by Austin-Hu** [comment]
Hi @tianjunwork ,

I couldn't reproduce the issue, by running "build.bat debug" in the command prompt of Visual Studio 2019, after following the Build steps [here](https://github.com/OpenVisualCloud/SVT-HEVC). So what's your reproducing step?

**Comment by tszumski** [comment]
Hi, I had the same issue today. This happen only in Visual Studio 2017 Debug version.
To fix this:
in file EbEncHandle.c before calling EbSystemResourceCtor(...) line 1181
few more variables have to be set for inputData :
inputData.compressedTenBitFormat
inputData.tileRowCount
inputData.tileColumnCount
inputData.encMode
inputData.speedControl

These values can be ctrl+c,ctrl+v from lines: 1118-1124

**Comment by Austin-Hu** [comment]
Hi @tszumski,

Please help create a PR for your [commit](https://github.com/tszumski/SVT-HEVC/commit/d12fb62bbc86df492dca89702e67fa5e27a5057b), thanks!

**Comment by tianjunwork** [comment]
@tszumski thx, yes, I  have vs 2017 installed.

**Comment by tianjunwork** [comment]
Hi @Austin-Hu, PR#334 shows that vs2019 debug build also crashes.

**Comment by 1480c1** [comment]
@tszumski's commit does fix debug builds it seems https://ci.appveyor.com/project/1480c1/svt-hevc/builds/26867999

**Comment by Austin-Hu** [comment]
Reproduced the SvtHevcEncApp.exe crashing issue, after compiling the debug version via VS 2019. And verified that PR #335 fixed this issue. Thanks, @tszumski !
