### ISSUE TITLE
Shared lib executable stack

### ISSUE THREAD

**Issue by Vascom** [OpenVisualCloud/SVT-HEVC#364]
Compiled shared lib has warning from rpmlint:

The binary declares the stack as executable. Executable stack is usually an
error as it is only needed if the code contains GCC trampolines or similar
constructs which uses code on the stack. One common source for needlessly
executable stack cases are object files built from assembler files which don't
define a proper .note.GNU-stack section.

The same problem in svt-vp9.

Solve it please.

**Comment by tianjunwork** [comment]
Hi @Austin-Hu , could you help take a look? Thank you.

**Comment by Austin-Hu** [comment]
The issue can be fixed by PR #366 as the same fix of SVT-VP9 PR #57  , and please also help verify it in your side, @Vascom. Thanks!

**Comment by Vascom** [comment]
Verified.
OK.
