### ISSUE TITLE
SVT-HEVC is blocked when flushing

### ISSUE THREAD

**Issue by Yeongjin-Jeong** [OpenVisualCloud/SVT-HEVC#367]
In any app (e.g. SvtHevcEncApp, ffmpeg, gstreamer) that uses the SVT-HEVC library, If I flush without attempting to encode anything, it will be block. 

In case of gstreamer plugin, blocking occurs when receiving EB_BUFFERFLAG_EOS buffer after sending EB_BUFFERFLAG_EOS buffer. So I worked around to avoid blocking when flushing without encoding in gstreamer.(https://github.com/OpenVisualCloud/SVT-HEVC/pull/340/commits/8886d14a74a24f3446f0c8d9ccc97f7cfacfa903)
```
#0  0x00007ffff64fb6d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fff991a6530) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7fff991a6530, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007ffff64fb7c8 in __new_sem_wait_slow (sem=0x7fff991a6530, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007ffff64fb839 in __new_sem_wait (sem=<optimized out>) at sem_wait.c:42
#4  0x00007ffff523a0e1 in EbBlockOnSemaphore (semaphoreHandle=<optimized out>) at /home/jin/Downloads/SVT-HEVC/Source/Lib/Codec/EbThreads.c:185
#5  0x00007ffff5239f0a in EbGetFullObject (fullFifoPtr=0x7fff991a6500, wrapperDblPtr=wrapperDblPtr@entry=0x7fffffff4e50) at /home/jin/Downloads/SVT-HEVC/Source/Lib/Codec/EbSystemResourceManager.c:688
#6  0x00007ffff520c2a5 in EbH265GetPacket (h265EncComponent=<optimized out>, pBuffer=0x7fffffff4e98, picSendDone=<optimized out>) at /home/jin/Downloads/SVT-HEVC/Source/Lib/Codec/EbEncHandle.c:3962
#7  0x00007ffff5c5d0c3 in gst_svthevc_enc_receive_frame (encoder=0x5555559848a0, got_packet=0x7fffffff4f10, send=1) at ../subprojects/gst-plugins-bad/ext/svthevcenc/gstsvthevcenc.c:1619
#8  0x00007ffff5c5d7af in gst_svthevc_enc_flush_frames (encoder=0x5555559848a0, send=1) at ../subprojects/gst-plugins-bad/ext/svthevcenc/gstsvthevcenc.c:1721
```

I created a gst-testcase to flush without attempting to encoding.(https://github.com/OpenVisualCloud/SVT-HEVC/pull/340/commits/87238453132701aa4a15d26a8c746ad82bb4f052) To create this situation in other apps, you need to modify your internal code to flush without encoding.

**Comment by Austin-Hu** [comment]
Hi @Yeongjin-Jeong ,

Please help check whether the [commit](https://github.com/Austin-Hu/SVT-HEVC/commit/af075be65447bcc044cd323e14a1b7591bc378df) could address the blocking (hang) issue or not. I didn't create its PR as I haven't verified with enough cases yet.

BTW, I didn't trace this "issue" (actually it can be worked around in application) with gstreamer, but did it with some [change ](https://github.com/Austin-Hu/SVT-HEVC/commit/1c6a9bed766ba9c8e6b6793a13aaac158db4563f) in SvtHevcEncApp.

Thanks!

**Comment by Yeongjin-Jeong** [comment]
@Austin-Hu , Thanks for your attention. I'll test it with your patch.

**Comment by Yeongjin-Jeong** [comment]
Hello @Austin-Hu, Sorry for testing too late. I tried my Gstreamer TC, and there seems to be no issue your patch. Thanks for your help :)

**Comment by Austin-Hu** [comment]
Thanks, @Yeongjin-Jeong ! We will go throught the PR review and merge process.
