### ISSUE TITLE
[SVT-HEVC]Some test found the recon.yuv and decoded.yuv have same file size, but the MD5 value is different in encMode[7-11] for 8K/4K resolution and in encMode[8-10] for 1080P/720P/480P resolutions.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-HEVC#368]
[Test environment]
OS: Ubuntu 18.04.2 LTS
SVT CommitID: f8f2a91

[Issue Description]
During run SVT-HEVC test with Commit ID f8f2a91, found the recon.yuv and decoded.yuv have same file size, but the MD5 value is different in encMode[7-11] for 8K/4K resolution and in encMode[8-10] for 1080P/720P/480P resolutions.

Test command line we used:
**SvtHevcEncApp** -i Netflix_Crosswalk_3840x2160_10bit_60Hz_P422.yuv  -b decode_test_M7_Netflix_Crosswalk_3840x2160_10bit_60Hz_P422_Q47_20.265  -w 3840  -h 2160  -bit-depth 10  -fps 60  -intra-period 55  -n 20  -encMode 7  -o recon.yuv  -compressed-ten-bit-format 0  -q 47  -color-format 2  -rc 0
**TAppDecoder** -b decode_test_M7_Netflix_Crosswalk_3840x2160_10bit_60Hz_P422_Q47_20.265 -o  decoded.yuv

**SvtHevcEncApp** -i ParkJoy_864x480_10bit_50Hz_P420.yuv  -b decode_test_M8_ParkJoy_864x480_10bit_50Hz_P420_Q33_20.265  -w 864  -h 480  -bit-depth 10  -fps 50  -intra-period 47  -n 20  -encMode 8  -o recon.yuv  -compressed-ten-bit-format 0  -q 33  -color-format 1  -rc 0
**TAppDecoder** -b decode_test_M8_ParkJoy_864x480_10bit_50Hz_P420_Q33_20.265 -o  decoded.yuv
![decode_2](https://user-images.githubusercontent.com/45022980/65310271-8ac6d100-dbc0-11e9-97ca-66605eaac43f.PNG)
![decode_1](https://user-images.githubusercontent.com/45022980/65310275-8e5a5800-dbc0-11e9-8dc7-530a1489d5a2.PNG)

**Comment by intelmark** [comment]
@GuCaixuan - Could you check if disabling the sao (-sao) and Deblocking (-dlf) filters will make any difference?  Thanks.

**Comment by Austin-Hu** [comment]
Hi @GuCaixuan ,

As the de-blocking and SAO filters would also be applied to the samples of each frame, after getting the reconstruction YUV data during decoding procedure, the reconstructed YUV always doesn't match with the decoded one from the encoded bitstream. I tried to disable those filters ("-dlf 1 -sao 0") and checked that the MD5 values of recon.yuv and decoded.yuv match (as 285c8da4b66ae534026d7130f84a51d0).

So please also check in your side and close this issue after your confirmation. BTW, it's great that your test case covers this, with filters disabled :) Thanks!

**Comment by GuCaixuan** [comment]
Hi @Austin-Hu， @intelmark,
The MD5 values of recon.yuv and decoded.yuv can match after disabling the sao (-sao 0 ) and Deblocking (-dlf 1 ) filters.
So close the issue. Thanks!
