### ISSUE TITLE
Work on up stream the gstreamer-plugin to gstreamer master

### ISSUE THREAD

**Issue by Yeongjin-Jeong** [OpenVisualCloud/SVT-HEVC#370]
This issue is for sharing the upstreaming process of gstreamer-plugin. (https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/gstreamer-plugin/git-patch)

Upstreaming is now in progress at https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/merge_requests/731.

**Comment by Yeongjin-Jeong** [comment]
Hello @tianjunwork, 
There was a request to change some properties of the svthevcenc element during the upstream process. After changing the preferred property naming and usage in gstreamer, I'll create a PR that applies the same to the independent gstreamer plugin.

**Comment by intelmark** [comment]
@Yeongjin-Jeong Does this issue need to stay open?  Is there any change needed in SVT-HEVC to support the upstreaming?

**Comment by Yeongjin-Jeong** [comment]
@intelmark, The upstream working is not finished yet. But I think there are no more interface change. So I'll close this issue, and I'll make PR soon with a patch that applies the review.
