### ISSUE TITLE
SvtHevcEncApp with tile separation

### ISSUE THREAD

**Issue by jefft0** [OpenVisualCloud/SVT-HEVC#372]
I used SvtHevcEncApp with `-tile_col_cnt` and `-tile_row_cnt` to encode a video with tiles. I have read that one of the purposes of HEVC is that the tile encoding is independent. But when I use openHEVC to decode only the data from one tile, the prediction is still looking "across the border" for pixels from neighboring tiles. In our application we need to be able to fetch only the data from one tile and decode it independently. How can I configure SVT-HEVC to encode tiles independently?

**Comment by intelmark** [comment]
Hi Jeff - Can you share your complete commandline for encoding?  Make sure that the UnrestrictedMotionVector parameter is set to 0 so that the motion vectors are constrained within the tile boundary

**Comment by jefft0** [comment]
Adding `-umv 0` fixed it. Thanks! FYI, here is my complete command line:

    ./SvtHevcEncApp -i input.yuv -w 640 -h 480 -color-format 2 -tile_col_cnt 2 -tile_row_cnt 2 -umv 0 -b output.hevc

**Comment by jefft0** [comment]
@intelmark, By the way, do you know of a similar parameter in SVT-AV1 which will encode the tiles separately?

**Comment by intelmark** [comment]
Currently SVT-AV1 doesn't support the tiling feature.  Could you explain a bit more about what this is needed for?

**Comment by jefft0** [comment]
The encoder has the command-line parameters `-tile-rows` and `-tile-columns`.
https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md#running-the-encoder

We want the producer to encode a large 4K video once with tiles, and let the consumer only fetch/decode the tiles that it wants (to reduce transmission bandwidth). This is why the tiles need to encoded independently.
