### ISSUE TITLE
-tune and not working,...

### ISSUE THREAD

**Issue by Selur** [OpenVisualCloud/SVT-HEVC#377]
using commit 3d68dd8397400bd70b48710f1b3b43a0bb3872f3 and:
```
ffmpeg -y -loglevel fatal -noautorotate -threads 8 -i "F:\TestClips&Co\Test-AAC-5.1.mp4" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f rawvideo - | SvtHevcEncApp -rc 0 -encMode 8 -tune 0 -i stdin -bit-depth 10 -w 640 -h 480 -color-format 1 -fps-num 25 -fps-denom 1 -profile 2 -n 834  -b "E:\Temp\Test-AAC-5.1_18_46_22_2410_02.265"
```
I get:
```
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:  SVT-HEVC Encoder Lib v1.4.1
SVT [build]  :  GCC 9.2.0        64 bit
LIB Build date: Sep 23 2019 15:04:08
-------------------------------------------
SVT [WARNING]: -tune is deprecated.
Number of logical cores available: 48
Number of PPCS 54
-------------------------------------------
SVT [config]: Main10 Profile    Tier (auto)     Level (auto)
SVT [config]: EncoderMode / Tune                                        : 8 / 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat / EncoderColorFormat     : 10 / 0 / 1
SVT [config]: SourceWidth / SourceHeight                                        : 640 / 480
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 25 / 0
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 32 / 17 / 1
SVT [config]: BitRateReduction / ImproveSharpness                               : 0 / 0
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV    : 1 / 1 / 0 / 0
-------------------------------------------
Encoding       834
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         834            25.00 fps                   988962              237.16 kbps


Channel 1
Average Speed:          361.35 fps
Total Encoding Time:    2308 ms
Total Execution Time:   2402 ms
Average Latency:        112 ms
Max Latency:            141 ms
```
The indicated `EncoderMode / Tune                                        : 8 / 1` is the concern here, since I used `-tune 0`.

Seeing that `-tune` is deprecated: will it just be removed or will it be replaced?

Also the output is broken. :(

**Comment by Austin-Hu** [comment]
Hi @Selur ,

The "-tune" option was deprecated with the 2 PRs (#263 & #325 ). And could you also upload the Test-AAC-5.1.mp4 video clip [here](https://drive.google.com/drive/folders/1mV-aGdiNSeEnWqx5R-c8XUPqqdpFpuFH)? Thanks!

**Comment by Selur** [comment]
I know that it was deprecated, but deprecated normally means that it will be renoved in an upcoming release not that it is broken. ;) (uploaded the file)

**Comment by tianjunwork** [comment]
Hi @Selur, the reason we still keep "-tune" api is not to break customer who already deployed SVT-HEVC. We will consider remove it in 2.0 release.

**Comment by Selur** [comment]
That I understand, but the fact is that it doesn't work as it should.
I used '-tune 0', but Tune 1 was used.
-> either it was broken to begin with or some change broke it ;)

**Comment by Austin-Hu** [comment]
Hi @Selur ,

Currently Tune 1 is always used, regardless of the "-tune" value set by user, to be compatible with applications which keep using the option.

As for the pipe broken issue, please refer to Issue #373 . Thanks!

**Comment by garloff** [comment]
"-tune is deprecated and ignored" would be a better message.

**Comment by tianjunwork** [comment]
Hi @garloff, if you run encoding with `-tune` with current master code, a warning message `SVT [WARNING]: -tune is deprecated.` will show up.

**Comment by garloff** [comment]
@tianjunwork - yes, I'm aware; I'm just proposing a slightly better wording ;-)

**Comment by tianjunwork** [comment]
Thank you @garloff , yes, it makes more sense. Will clean it up with some other things together.
