### ISSUE TITLE
entropy_coding_sync_enabled_flag

### ISSUE THREAD

**Issue by jefft0** [OpenVisualCloud/SVT-HEVC#378]
HEVC supports the entropy_coding_sync_enabled_flag. Is there a way in SVT-HEVC to encode using entropy coding?

**Comment by tianjunwork** [comment]
Hi @jefft0, entropy coding is part of SVT-HEVC encoder, and actually is used in all modern video standards. Could you be more specific about what you are requesting?

**Comment by megapro17** [comment]
> Hi @jefft0, entropy coding is part of SVT-HEVC encoder, and actually is used in all modern video standards. Could you be more specific about what you are requesting?

https://www.parabolaresearch.com/blog/2013-12-01-hevc-wavefront-animation.html
he wanted to create this animation

**Comment by tianjunwork** [comment]
Thanks @megapro17
`entropy_coding_sync_enabled_flag` is always set to 0 in SVT-HEVC. wavefront-based parallel processing is not used in SVT-HEVC, instead its own segment-based parallelism in a wave front manner.
For more parallel processing information about SVT-HEVC, please find at https://01.org/svt.

**Comment by megapro17** [comment]
It's possible to create similar animation to see the difference?

**Comment by tianjunwork** [comment]
I guess it is possible. What you need is to print out the coordinates and size of the segment being processed in EncDec kernel. You do need to dig into the source code. Then mapping the segments within the frame to create multiple images for animation.
