### ISSUE TITLE
support for macOS?

### ISSUE THREAD

**Issue by tessus** [OpenVisualCloud/SVT-HEVC#38]
Is this supported on macOS?

As far as I could find out the Mac Pro uses Xeon processors...

**Comment by hassount** [comment]
@tessus 
Thank you very much for your feedback. 
Currently SVT-HEVC does not have a support for MAC OS, however, we welcome contributions for adding such support.

**Comment by tessus** [comment]
> we welcome contributions for adding such support.

What exactly would this entail? Is it just the build script that needs to be adjusted, or does assembly code have to be re-written?

**Comment by hassount** [comment]
no assembly code to be re-written, I believe it would be some cmake / build scrip changes along with some compiler flags to make sure the code builds, after that it should just run.

**Comment by tianjunwork** [comment]
@mypopydev what is your insight about the 3rd and 4th question from @tessus?

**Comment by tessus** [comment]
Yep, I really would like to hear the answers, otherwise it makes no sense for me to get it working on macOS and then no being able to actually use it.

**Comment by hassount** [comment]
@tessus 
I apologize for the late reply, please find below my answers:

- For point 1, could you please create an issue, stating which options do you need clarity on ? 
- This should be feasible by changing the CMake files of the library to create a static and link it to the application, if you require assistance with this, please add a separate issue for this item too. 
- Definitely not, not even gpl is needed, we'll be addressing this in the next commits, this is a free library licensed under the BSD+Patent license and so you can use it as you wish. 
- This is already in progress, we have already opened the PR and are working on feedback from the ffmpeg community.

**Comment by tessus** [comment]
@hassount Thank you very much for your reply.

I will open separate issues for item 1 and 2.

> Definitely not, not even gpl is needed, we'll be addressing this in the next commits, this is a free library licensed under the BSD+Patent license and so you can use it as you wish.

I've noticed that the `--enable-nonfree` has been removed from the `README.txt`. Thanks.

> This is already in progress, we have already opened the PR and are working on feedback from the ffmpeg community.

Have you already sent the new patch to the ffmpeg-devel mailing list?

**Comment by 1480c1** [comment]
So, I've got it to 94%, <https://travis-ci.org/1480c1/SVT-HEVC/jobs/499613916#L549> however I am erroring out at `Undefined symbols for architecture x86_64:`. It would be nice if someone could help. My knowledge of C comes from stackoverflow and looking at some man pages, on windows.

Idk if my modifications would actually work since I'm basically looking if the same headers from linux are present on Mac and changing `#if __linux__` to ``#if __linux__ || __APPLE__`` for some and I had a rough time with cpu_set_t.

**Comment by 1480c1** [comment]
This can be closed
