### ISSUE TITLE
what is the meaning of eb_ before almost all files?

### ISSUE THREAD

**Issue by laxusvip** [OpenVisualCloud/SVT-HEVC#389]
what is the meaning of eb_

**Comment by 1480c1** [comment]
The original company's name was [eBrisk](https://www.prnewswire.com/news-releases/ebrisk-video-enables-real-time-h265hevc-encoding-of-4k60fps10-bit-hdr-video-on-single-intel-xeon-e5-2690-v4-601292936.html)
