### ISSUE TITLE
look ahead 0 with10-bit input encodes to different bitstreams run-to-run

### ISSUE THREAD

**Issue by intelmark** [OpenVisualCloud/SVT-HEVC#414]
Seeing differences in the encoded bitstream run-to-run when compressing 10bit and using -lad 0 (file sizes are different as well).  This issue became apparent when adding the YUV422 10-bit compressed support.

Here are some examples:
SvtHevcEncApp.exe -i ParkJoy_864x480_10bit_50Hz_P420.yuv -w 874 -h 480 -bit-depth 10 -lad 0 -b test1.hevc 
SvtHevcEncApp.exe -i ParkJoy_864x480_10bit_50Hz_P420.yuv -w 874 -h 480 -bit-depth 10 -lad 0 -b test2.hevc – different

SvtHevcEncApp.exe -i ParkJoy_864x480_10bit_50Hz_P420.yuv -w 874 -h 480 -bit-depth 10  -b test1.hevc 
SvtHevcEncApp.exe -i ParkJoy_864x480_10bit_50Hz_P420.yuv -w 874 -h 480 -bit-depth 10  -b test2.hevc – same

SvtHevcEncApp.exe -i ParkJoy_1920x1080_50p_8bit.yuv -w 1920 -h 1080  -lad 0 -n 200 -b test1.hevc
SvtHevcEncApp.exe -i ParkJoy_1920x1080_50p_8bit.yuv -w 1920 -h 1080  -lad 0 -n 200 -b test2.hevc – same

SvtHevcEncApp.exe -i Netflix_Crosswalk_3840x2160_10bit_60Hz_P420.yuv -w 3840 -h 2160 -lad 0 -n 200 -b test1.hevc
SvtHevcEncApp.exe -i Netflix_Crosswalk_3840x2160_10bit_60Hz_P420.yuv -w 3840 -h 2160 -lad 0 -n 200 -b test1.hevc – different

**Comment by Austin-Hu** [comment]
For PR #[455](https://github.com/OpenVisualCloud/SVT-HEVC/pull/455), also verified that:
1. The MD5 sum of encoded bitstreams are the same (with default LAD 17), with the PR applied or not;

2. No R2R issue for:
       420, 8/10bit, lad 0/17
       422, 8/10bit, lad 0/17
       444, 8/10bit, lad 0/17

3. No encoding performance (FPS) gap with the PR applied or not:
                                                                      No PR#455         PR#455
                                                                      LAD 17   LAD 0   LAD 17   LAD 0
7680x3840_8bit_P420 (417 frames):              33.39     35.32     32.66     34.53
7680x3840_8bit_P444 (417 frames):              18.74     19.71     16.68     18.08
1920x1080_8bit_60Hz_P420 (5000 frames):   226.44   204.67   228.87   203.35
1920x1080_8bit_60Hz_P444 (5000 frames):   251.42   238.67   249.14   231.04
