### ISSUE TITLE
Can HDR support be added to the ffmpeg-plugin?

### ISSUE THREAD

**Issue by five82** [OpenVisualCloud/SVT-HEVC#430]
Can the -hdr flag be added to the ffmpeg-plugin? I see references to it in old ffmpeg upstream patches but it was never added to the plugin here. Thanks.

https://patchwork.ffmpeg.org/patch/12528/

**Comment by tianjunwork** [comment]
Hi Jing @jsunintel , could you help with this?

**Comment by jsunintel** [comment]
No, we can't do that yet. The FFmpeg community is against how we are implementing the HDR feature in SVT HEVC lib, and that is not changed.

**Comment by tianjunwork** [comment]
Hi @five82, to be clear, you were asking adding HDR to ffmpeg plugin in this repo, right? Or to the upstream patch?

**Comment by five82** [comment]
Hi @tianjunwork, it was for the ffmpeg plugin in this repo. Thanks.

**Comment by tianjunwork** [comment]
Hi Jing @jsunintel, do you think we can just add HDR for our own ffmpeg plugin?

**Comment by tianjunwork** [comment]
Hi @five82, SVT-HEVC -hdr only signals HDR10 input, does this fit your needs? If so, we can quickly expose it in the ffmpeg plugin. 
If the ask is to support other formats of HDR, that is a more stretching goal.

**Comment by five82** [comment]
Exposing the -hdr flag to allow HDR10 input only is fine. Thanks again @tianjunwork.
