### ISSUE TITLE
Does SVT-HEVC support SHVC?

### ISSUE THREAD

**Issue by Wilson-Ian** [OpenVisualCloud/SVT-HEVC#440]
As my understanding, currently there is one software SHM support it as reference, which doesn't have any optimization.  Just confirm with experts  here whether SVT support the SHVC ecoding?  

Thanks very much!

Wilson

**Comment by tianjunwork** [comment]
Hi @Wilson-Ian, SVT-HEVC supports temporal scalability out of the three main types of video scalability–temporal, spatial, and quality. Please refer to https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/Docs/svt-hevc_encoder_user_guide.md#1-hierarchical-coding-structure-parameters.

**Comment by Wilson-Ian** [comment]
Thanks @tianjunwork！ As you previously mentioned, I read  the guideline about the LD and RA of the Hierarchical coding of GOP but seems they are not for SHVC purpose right?  do we have plan or roadmap to support SHVC for temporal, spatial or quality based?  Thanks again!

**Comment by tianjunwork** [comment]
Hi @Wilson-Ian, you are welcome. No, they are not for SHVC purpose. SHVC is not on the current roadmap.
