### ISSUE TITLE
[SVT-HEVC]For 4K and 480P resolution, the bitstream display garbage screen after setting "-nb" parameter to encode.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-HEVC#443]
Test environment]
OS: Ubuntu 16.04.5 LTS
SVT CommitID: 4b40262

During run SVT-HEVC test with Commit ID 4b40262, found that the bitstream display garbage screen after setting "-nb" parameter to encode for 4K and 480 resolution.
I also checked this issue on 19144a6(CommitID ) version, it’s passed.

Sample Command line
SvtHevcEncApp -i Netflix_Crosswalk_3840x2160_10bit_60Hz_P420.yuv  -b buffered_test_M8_Netflix_Crosswalk_3840x2160_10bit_60Hz_P420_Q49_20.265  -w 3840  -h 2160  -bit-depth 10  -fps 60  -intra-period 55  -n 20  -encMode 8  -compressed-ten-bit-format 0  -q 49  -color-format 1  -rc 0  **-nb 20**

SvtHevcEncApp -i ParkJoy_864x480_10bit_50Hz_P420.yuv  -b buffered_test_M1_ParkJoy_864x480_10bit_50Hz_P420_Q48_20.265  -w 864  -h 480  -bit-depth 10  -fps 50  -intra-period 47  -n 20  -encMode 1  -compressed-ten-bit-format 0  -q 48  -color-format 1  -rc 0  **-nb 20**
<img width="506" alt="4k_480p" src="https://user-images.githubusercontent.com/45022980/70486514-1a7b7c00-1b2d-11ea-90f3-8baa4bdd2fa2.PNG">

**Comment by tianjunwork** [comment]
I can reproduce on tip but 19144a6(CommitID) also fails.
