### ISSUE TITLE
Memory Leaks reported with Windows debug and y4m encoding

### ISSUE THREAD

**Issue by intelmark** [OpenVisualCloud/SVT-HEVC#465]
Using master branch and encoding a 1080p y4m file using VS 2017 on Windows - debug build

-i c:/testfiles/BQTerrace_1920x1080_60p_i420_8bit.y4m -n 50

Getting numerous "aligned memory leaked" messages after encoding

-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.7.0
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Feb  5 2020 14:42:22
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 72
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 30 / 1 / 32 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
SVT Memory Usage:
    total allocated memory:       5.60 GB
        malloced memory:          4.36 GB
        callocated memory:        41.09 MB
        allocated aligned memory: 1.20 GB
    mutex count: 517
    semaphore count: 264
    thread count: 55
    hash table fulless: 0.095391, hash bucket is healthy
top 10 malloced memory locations:
(1.42 GB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:1174
(1.21 GB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:415
(289.86 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbCodingUnit.c:60
(239.06 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbCodingUnit.c:61
(217.44 MB): C:\repos\SVT-AV1\Source\Lib\Encoder\Codec\EbEncHandle.c:3355
(143.05 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbBitstreamUnit.c:40
(119.06 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:98
(95.52 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbModeDecisionProcess.c:103
(77.44 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureControlSet.c:418
(54.69 MB): C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbMotionEstimationContext.c:117
Encoding        50
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
          50            30.00 fps                   590923              2836.43 kbps

Channel 1
Average Speed:          0.693 fps
Total Encoding Time:    72195 ms
Total Execution Time:   80230 ms
Average Latency:        63696 ms
Max Latency:            72050 ms
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L100
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L84
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPictureBufferDesc.c:L92
SVt: aligned memory leaked at C:\repos\SVT-AV1\Source\Lib\Common\Codec\EbPict

**Comment by tianjunwork** [comment]
Pls post it to AV1:)

**Comment by intelmark** [comment]
never mind :(
