### ISSUE TITLE
umv flag mode isn't reflected in the  SVT mode when using docker

### ISSUE THREAD

**Issue by raztexel** [OpenVisualCloud/SVT-HEVC#470]
Running:
 docker run -v SampleVideos:/home  openvisualcloud/xeon-ubuntu1804-media-ffmpeg /bin/bash -c "dd if=/dev/urandom bs=115200 count=300 of=test.yuv && ffmpeg -f rawvideo -vcodec rawvideo -s 320x240 -r 30 -pix_fmt yuv420p  -i test.yuv -c:v libsvt_hevc -umv 0 -y test.mp4"

Printout banner:
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV 		: 1 / 1 / 0 / 0

 docker run -v SampleVideos:/home  openvisualcloud/xeon-ubuntu1804-media-ffmpeg /bin/bash -c "dd if=/dev/urandom bs=115200 count=300 of=test.yuv && ffmpeg -f rawvideo -vcodec rawvideo -s 320x240 -r 30 -pix_fmt yuv420p  -i test.yuv -c:v libsvt_hevc -umv 1 -y test.mp4"

Printout banner is the same:
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV 		: 1 / 1 / 0 / 0

**Comment by raztexel** [comment]
With umv 0 and umv 1 the banner prints the same UMV mode

**Comment by intelmark** [comment]
@raztexel - Can you confirm you rebuilt the SVT-HEVC plugin for ffmpeg using the updated patch file?

**Comment by raztexel** [comment]
I have just used the docker command. I haven’t built SVT-HEVC.

This is what I have run:

docker run -v SampleVideos:/home openvisualcloud/xeon-ubuntu1804-media-ffmpeg /bin/bash -c "dd if=/dev/urandom bs=115200 count=300 of=test.yuv && ffmpeg -f rawvideo -vcodec rawvideo -s 320x240 -r 30 -pix_fmt yuv420p -i test.yuv -c:v libsvt_hevc -umv 1 -y test.mp4"

**Comment by raztexel** [comment]
is this version support tiling or should I use different version?

**Comment by tianjunwork** [comment]
Hi @raztexel , are you using the docker image from OpenVisualCloud/Dockerfiles? If so, it only build the latest release tag. `- umv` in ffmpeg is in the master which is after 1.4.3 release tag.

**Comment by tianjunwork** [comment]
Hi @raztexel , do you need any more help about `-umv` parameter? If not, could you close? Thank you.
