### ISSUE TITLE
Which SVT specific flag are available with ffmpeg

### ISSUE THREAD

**Issue by raztexel** [OpenVisualCloud/SVT-HEVC#479]
Is there a document that describes the SVT specific flag the ffmpeg-svt supports such as umv, tile_row, tile_column. Is there a way to pass flag directly to SVT using a flasg such as -x265-params for x265?

**Comment by 1480c1** [comment]
Currently, there are no `-svt-params` or similar for any of the SVT encoder ffmpeg plugins, although it may be possible for SVT-AV1

**Comment by tianjunwork** [comment]
Hi @raztexel , https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L518 shows all the flags ffmpeg plugin supports, which map to the encoder parameters in https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L518

**Comment by tianjunwork** [comment]
Hi @raztexel , any more questions around this topic? If not, could you close? Thank you.

**Comment by raztexel** [comment]
answer the question
