### ISSUE TITLE
SVT HEVC encoder crashes with the particular HEVC standard test sequence SlideShow

### ISSUE THREAD

**Issue by PDX-Runner** [OpenVisualCloud/SVT-HEVC#481]
latest code crashes at line 660 of EbPictureOperators_C.c with the below command. asm code has the same issue.

-i SlideShow_1280x720.yuv -w 1280 -h 720 -asm 0 -encMode 0 -intra-period 100 -scd 0 -rc 0 -q 22 -n 100 -b SlideShow_1280x720_SVTMODE0_22_SVT.265

**Comment by PDX-Runner** [comment]
it is the same issue as https://github.com/OpenVisualCloud/SVT-HEVC/issues/55

**Comment by Austin-Hu** [comment]
Hi @PDX-Runner ,

Please check whether PR #482 works. Thanks! (BTW, please set "-asm" with 1, if the encoding is too slow in your side.)
