### ISSUE TITLE
intra-period impact on latency

### ISSUE THREAD

**Issue by joyceliaoxy** [OpenVisualCloud/SVT-HEVC#502]
Hi there,

I want to test if intra-period will impact on encoder latency, and downbelow is the test command I use, except intra-period parameter, all the other parameters i am using the configuration of a pipeline which is a live stream encoding and decoding for real-time VR purpose. 

numactl --cpubind=0 --membind=0 ./SvtHevcEncApp -i /home/xiaoxime/Videos/8k2D_musician_360_h265.yuv -w 7680 -h 3840 -intra-period 4 -fps 30 -scd 0 -pred-struct 0 -irefresh-type 0 -constrd-intra 1 -rc 1 -tbr 10000000 -temporal-id 0 -ss 0 -b /home/xliao/im360/encoder_test/test_latency_3.bin -lad 0 -nb 100 -n 416 -inj 1 -inj-frm-rt 30 -sao 1 -encMode 9 -fpsinvps 0 -tile_col_cnt 6 -tile_row_cnt 12  -q 32 -tile_slice_mode 1

**Comment by tianjunwork** [comment]
Hi @joyceliaoxy , 
`-sao 1` is not needed, the default is 1 already.
`-q 32` is not needed, since you already use `-rc 1 -tbr 10000000`, vbr mode.
`-nb` can't be used in product pipeline. It is only for perf testing purpose.

Sure please go ahead with your test of `-intra-period` with different value.

**Comment by joyceliaoxy** [comment]
Hi Jun,

I tried downbelow command, the latency still have significant rise compared with intra-period is some big value, for instance 30.
numactl --cpubind=0 --membind=0 ./SvtHevcEncApp -i /Videos/8k2D_musician_360_h265.yuv -w 7680 -h 3840 -intra-period 4 -fps 30 -scd 0 -pred-struct 0 -irefresh-type 0 -constrd-intra 1 -rc 1 -tbr 10000000 -temporal-id 0 -ss 0 -b /home/xliao/im360/encoder_test/test_latency_3.bin -lad 0 -n 416 -encMode 9 -fpsinvps 0 -tile_col_cnt 6 -tile_row_cnt 12 -tile_slice_mode 1

**Comment by tianjunwork** [comment]
Pls send your perf data with different command lines and lscpu output

**Comment by tianjunwork** [comment]
If no more help is needed from us, could you close the issue?
