### ISSUE TITLE
Documentation about distributed_encoder (svt based)

### ISSUE THREAD

**Issue by raztexel** [OpenVisualCloud/SVT-HEVC#511]
Hi,
Is there documentation for the distributed encoder and ffmpeg based on libsvt?
Is the SVT-HEVC support tiling same as "distributed_encoder"?
Thanks

**Comment by tianjunwork** [comment]
Hi @raztexel, what is `distributed encoder`?

**Comment by raztexel** [comment]
It’s the ffmpeg created in the bed immersive project.
Regards
Raz
