### ISSUE TITLE
multi_channel_test failures

### ISSUE THREAD

**Issue by intelmark** [OpenVisualCloud/SVT-HEVC#519]
P422 and P444 tests fail.
P420 tests pass

encoders/SvtHevcEncApp -nch 4 -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b bitstreams/     multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4.265 bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4_1.265 bitstreams/                                                                     multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4_2.265 bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4_3.265  -errlog bitstreams/                                                          multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4.errlog bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4_1.errlog bitstreams/                                                               multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4_2.errlog bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4_3.errlog  -w 1280 1280 1280 1280  -h 720 720 720 720  -bit-depth 8 8 8 8  -      fps 50 50 50 50  -intra-period 47 47 47 47  -n 40 40 40 40  -lp 1  -encMode 1 1 1 1  -compressed-ten-bit-format 0 0 0 0  -q 35 35 35 35  -color-format 2 2 2 2  -rc 0 0 0 0  > bitstreams/                                                   multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q35_nch4.txt
------------Failed2-------------

encoders/SvtHevcEncApp -nch 4 -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv  -b bitstreams/     multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4.265 bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4_1.265 bitstreams/                                                                     multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4_2.265 bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4_3.265  -errlog bitstreams/                                                          multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4.errlog bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4_1.errlog bitstreams/                                                               multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4_2.errlog bitstreams/multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4_3.errlog  -w 1280 1280 1280 1280  -h 720 720 720 720  -bit-depth 8 8 8 8  -      fps 50 50 50 50  -intra-period 47 47 47 47  -n 40 40 40 40  -lp 1  -encMode 1 1 1 1  -compressed-ten-bit-format 0 0 0 0  -q 40 40 40 40  -color-format 3 3 3 3  -rc 0 0 0 0  > bitstreams/                                                   multi_channel_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q40_nch4.txt
------------Failed2-------------

**Comment by intelmark** [comment]
Took a look at the last issue multi_channel_test with 422 and 444 color formats, and confirmed it easily reproducible on Windows. Same multi channel test with 420 color format seems to be working.

(e.g.)
-nch 4 -i /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4.265 /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4_1.265 /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4_2.265 /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4_3.265  -errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4.errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4_1.errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4_2.errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P422_Q46_nch4_3.errlog  -w 1280 1280 1280 1280  -h 720 720 720 720  -bit-depth 8 8 8 8  -fps 50 50 50 50  -intra-period 47 47 47 47  -n 40 40 40 40  -encMode 2 2 2 2  -compressed-ten-bit-format 0 0 0 0  -q 46 46 46 46  -color-format 2 2 2 2  -rc 0 0 0 0  

produces 4 streams with differences

while

-nch 4 -i /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv /testfiles/DucksTakeOff_1280x720_8bit_50Hz_P420.yuv  -b /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4.265 /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4_1.265 /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4_2.265 /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4_3.265  -errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4.errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4_1.errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4_2.errlog /testfiles/multi_channel_test_M2_DucksTakeOff_1280x720_8bit_50Hz_P420_Q46_nch4_3.errlog  -w 1280 1280 1280 1280  -h 720 720 720 720  -bit-depth 8 8 8 8  -fps 50 50 50 50  -intra-period 47 47 47 47  -n 40 40 40 40  -encMode 2 2 2 2  -compressed-ten-bit-format 0 0 0 0  -q 46 46 46 46  -color-format 1 1 1 1  -rc 0 0 0 0
produces 4 identical streams.

**Comment by tianjunwork** [comment]
Bug of multi channel feature with non 420 input.

**Comment by tianjunwork** [comment]
Duplicate with #371
