### ISSUE TITLE
asm_test failures

### ISSUE THREAD

**Issue by intelmark** [OpenVisualCloud/SVT-HEVC#520]
encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_0.265  -errlog bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_0.errlog  -w
1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 0  -compressed-ten-bit-format 0  -q 44  -color-format 2  -rc 0  > bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_0.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_0.265  -errlog bitstreams/                            
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_0.errlog  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 0  -compressed-ten-bit-format 0  -q 44  -color-format 2  -rc 0  > bitstreams/
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_0.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_1.265  -errlog bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_1.errlog  -w
1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 1  -compressed-ten-bit-format 0  -q 44  -color-format 2  -rc 0  > bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_1.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_1.265  -errlog bitstreams/                            
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_1.errlog  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 1  -compressed-ten-bit-format 0  -q 44  -color-format 2  -rc 0  > bitstreams/
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q44_1.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
----------compare_bitstream0------------
----------2 compare_bitstreamFalse------------
------------Failed5-------------

encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_0.265  -errlog bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_0.errlog  -w
1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 0  -compressed-ten-bit-format 0  -q 39  -color-format 3  -rc 0  > bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_0.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_0.265  -errlog bitstreams/                            
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_0.errlog  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 0  -compressed-ten-bit-format 0  -q 39  -color-format 3  -rc 0  > bitstreams/
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_0.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_1.265  -errlog bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_1.errlog  -w
1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 1  -compressed-ten-bit-format 0  -q 39  -color-format 3  -rc 0  > bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_1.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P444.yuv  -b bitstreams/asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_1.265  -errlog bitstreams/                            
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_1.errlog  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 1000  -lp 1  -encMode 1  -asm 1  -compressed-ten-bit-format 0  -q 39  -color-format 3  -rc 0  > bitstreams/
asm_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P444_Q39_1.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
----------compare_bitstream0------------
----------2 compare_bitstreamFalse------------
------------Failed5-------------

**Comment by tianjunwork** [comment]
Hi Mark, it not quite clear what problem are from reading above comments.

**Comment by tianjunwork** [comment]
Duplicate with #371
