### ISSUE TITLE
defield_test failures

### ISSUE THREAD

**Issue by intelmark** [OpenVisualCloud/SVT-HEVC#521]
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.265  -errlog bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.             errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 4  -interlaced-video 1  -compressed-ten-bit-format 0  -q -color-format 1  -rc 0  > bitstreams/                           defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.265  -errlog bitstreams/                                  defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 4  -interlaced-video 1  -compressed-ten-bit-format 0  -q 42  -     color-format 1  -rc 0  > bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.265  -errlog bitstreams/                                                         defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 4  -interlaced-video 1  -compressed-ten-bit-format 0  -      q 42  -color-format 1  -rc 0  > bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.txt
---------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.265  -errlog bitstreams/                    defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 4  -interlaced-video 1  -compressed-ten-bit-format 0  -      q 42  -color-format 1  -rc 0  > bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.txt------------
---------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
----------compare_bitstream0------------
----------2 compare_bitstreamFalse------------
------------Failed5-------------

encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.265  -errlog bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.             errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 8  -interlaced-video 1  -compressed-ten-bit-format 0  -q -color-format 1  -rc 0  > bitstreams/                           defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.265  -errlog bitstreams/                                  defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 8  -interlaced-video 1  -compressed-ten-bit-format 0  -q 42  -     color-format 1  -rc 0  > bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q42_1_1.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.265  -errlog bitstreams/                                                         defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 8  -interlaced-video 1  -compressed-ten-bit-format 0  -      q 42  -color-format 1  -rc 0  > bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.265  -errlog bitstreams/                    defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 8  -interlaced-video 1  -compressed-ten-bit-format 0  -      q 42  -color-format 1  -rc 0  > bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q42_0_1.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
----------compare_bitstream0------------
----------2 compare_bitstreamFalse------------
------------Failed5-------------

encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.265  -errlog bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.             errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 4  -interlaced-video 0  -compressed-ten-bit-format 0  -q -color-format 1  -rc 0  > bitstreams/                           defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.265  -errlog bitstreams/                                  defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 4  -interlaced-video 0  -compressed-ten-bit-format 0  -q 33  -     color-format 1  -rc 0  > bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.265  -errlog bitstreams/                                                         defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 4  -interlaced-video 0  -compressed-ten-bit-format 0  -      q 33  -color-format 1  -rc 0  > bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.265  -errlog bitstreams/                    defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 4  -interlaced-video 0  -compressed-ten-bit-format 0  -      q 33  -color-format 1  -rc 0  > bitstreams/defield_test_M4_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
----------compare_bitstream0------------
----------2 compare_bitstreamFalse------------
------------Failed5-------------

encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.265  -errlog bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.             errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 8  -interlaced-video 0  -compressed-ten-bit-format 0  -q -color-format 1  -rc 0  > bitstreams/                           defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.265  -errlog bitstreams/                                  defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.errlog  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 1000  -lp 1  -separate-fields 1  -encMode 8  -interlaced-video 0  -compressed-ten-bit-format 0  -q 33  -     color-format 1  -rc 0  > bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_Q33_1_0.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.265  -errlog bitstreams/                                                         defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 8  -interlaced-video 0  -compressed-ten-bit-format 0  -      q 33  -color-format 1  -rc 0  > bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.txt
----------Calling subprocess enc_cmd=encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420_fields.yuv  -b bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.265  -errlog bitstreams/                    defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.errlog  -w 1920  -h 540  -bit-depth 8  -fps 60  -intra-period 55  -n 2000  -lp 1  -separate-fields 0  -encMode 8  -interlaced-video 0  -compressed-ten-bit-format 0  -      q 33  -color-format 1  -rc 0  > bitstreams/defield_test_M8_Fallout4_1920x1080_8bit_60Hz_P420_fields_Q33_0_0.txt------------
----------exit_code=0------------
----------2 exit_code=0------------
----------COMPARE not 1
----------compare_bitstream0------------
----------2 compare_bitstreamFalse------------
------------Failed5-------------

**Comment by tianjunwork** [comment]
Hi Mark, it not quite clear what problem are from reading above comments.

**Comment by tianjunwork** [comment]
Fixed by #534
