### ISSUE TITLE
gstreamer plugin failed to build in VS 2017

### ISSUE THREAD

**Issue by dudulashok** [OpenVisualCloud/SVT-HEVC#529]
Please help me find the issue. Attached meson-log.txt file for your reference.

C:\SVT-HEVC\gstreamer-plugin>ninja -C build
ninja: Entering directory `build'
[1/2] Compiling C object gstsvthevcenc@sha/gstsvthevcenc.c.obj
FAILED: gstsvthevcenc@sha/gstsvthevcenc.c.obj
cl @gstsvthevcenc@sha/gstsvthevcenc.c.obj.rsp
c:\svt-hevc\gstreamer-plugin\gstsvthevcenc.h(13): fatal error C1083: Cannot open include file: 'EbApi.h': No such file or directory
ninja: build stopped: subcommand failed.
[meson-log.txt](https://github.com/OpenVisualCloud/SVT-HEVC/files/4523121/meson-log.txt)

**Comment by tianjunwork** [comment]
Hi @dudulashok , it seems that you didn't install svt header files. `cmake -P SVT-HEVC\Build\Windows\Source\Lib\cmake_install.cmake`. Pls make sure you follow the build steps. We will double check on our side.
Btw gst plugin is upstreamed already. It's better to use this one. We plan to take down the gst plugin in this repo.
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/731?commit_id=663aeb2131a12d38a0729129ca8709645ca3afd5.

**Comment by dudulashok** [comment]
'EbApi.h' is part of API, not under Lib. I tried twice in my side, but got the same error.

**Comment by tianjunwork** [comment]
Yes, both header files and libs should be installed. I will try on my side.

**Comment by tianjunwork** [comment]
Fixed in the latest commit: cmake -P SVT-HEVC\Build\Windows\cmake_install.cmake

**Comment by dudulashok** [comment]
Thank you. It's working, but the below error is coming.
(gst-inspect-1.0:8348): GStreamer-WARNING **: 02:59:13.376: Failed to load plugin 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstsvthevcenc.dll': 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstsvthevcenc.dll': The specified module could not be found.
No such element or plugin 'svthevcenc'

gstreamer is unable to load the dlls. This may not be related to svt hevc, but any step missed in the readme doc?

**Comment by tianjunwork** [comment]
Did you install?
```T
hen the plugin can be compiled and installed using Ninja:

meson -Dprefix=%GSTREAMER_1_0_ROOT_X86_64% build && ninja -C build && ninja -C build install
```

**Comment by dudulashok** [comment]
Hi @tianjunwork 
Yes, I have installed and getting the logs same as yours. After that while verifying the installation using the command "gst-inspect-1.0 svthevcenc", it is showing "No such element or plugin "svthevcenc'". I think something is missing. I'm trying to find the issue, at the same time if you check in your side will be helpful.

**Comment by tianjunwork** [comment]
```
export GST_DEBUG_FILE=
export GST_DEBUG="*:6"
```
You can enable log to see what is going on.
If the plugin is correctly installed, I never see this error before. May be related to your env.

**Comment by tianjunwork** [comment]
Hi @dudulashok, hope that gst plugin works on your side now. Any further assist needed?
