### ISSUE TITLE
release source filename missing app info

### ISSUE THREAD

**Issue by th0ma7** [OpenVisualCloud/SVT-HEVC#539]
he filename for all releases doesn't include the package name but rather only the version:
```
https://github.com/OpenVisualCloud/SVT-HEVC/archive/v1.4.3.zip
https://github.com/OpenVisualCloud/SVT-HEVC/archive/v1.4.3.tar.gz
```
This will eventually cause issues for packagers.
At the very least `svt-hevc_v1.4.3.tar.gz` or similar would be meaningful

**Comment by tianjunwork** [comment]
Release source code package is auto generated by Github. 
When downloading through Github web page, it looks correct with `SVT-HEVC`:
![image](https://user-images.githubusercontent.com/4551215/83293504-c0d14180-a1a0-11ea-800d-5124fc1567eb.png)

**Comment by th0ma7** [comment]
But from the release web pate archive download URL doesn't include the `SVT-HEVC` part.

**Comment by 1480c1** [comment]
That seems to be a browser/html thing https://stackoverflow.com/questions/3102226/how-to-set-name-of-file-downloaded-from-browser

**Comment by th0ma7** [comment]
You are absolutely right, I thought this was an exception but no.  Closing the issue.

**Comment by 1480c1** [comment]
Depending on the project, I would recommend trying to use the headers to try to get the filename or use `-J` with curl if possible

```bash
# Get filename
filename=$(curl -IL https://api.github.com/repos/OpenVisualCloud/SVT-HEVC/tarball/v1.4.3 | tr ' ' '\n' | grep filename | cut -d= -f2)
curl -oL "${filename:-SVT-HEVC_v1.4.3}" https://api.github.com/repos/OpenVisualCloud/SVT-HEVC/tarball/v1.4.3
```
or
```bash
curl -OJL https://api.github.com/repos/OpenVisualCloud/SVT-HEVC/tarball/v1.4.3 
```
