### ISSUE TITLE
Is there any way I can use params like MasterDisplay, HighDynamicRangeInput in SVT ffmpeg plugins?

### ISSUE THREAD

**Issue by LSC527** [OpenVisualCloud/SVT-HEVC#544]
Is there any params I can use other than showed in https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L518

**Comment by 1480c1** [comment]
Not yet

**Comment by 1480c1** [comment]
There is an `hdr` param though https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L598

**Comment by LSC527** [comment]
OK， thx
