### ISSUE TITLE
-hdr not working in SVT ffmpeg-plugin

### ISSUE THREAD

**Issue by LSC527** [OpenVisualCloud/SVT-HEVC#546]
ffmpeg -y -s 1920x1080 -pix_fmt yuv420p10le -i xx.yuv -c:v libsvt_hevc -rc 1 -b:v 15M -preset 5 -hdr 1 xx.mp4

**Comment by LSC527** [comment]
It seems that there is no difference  in my out put file whether I set -hrd 1 or not

**Comment by LSC527** [comment]
> [https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-li](https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L598)

**Comment by intelmark** [comment]
Are the bitstreams the same when compared using a binary byte comparison or running md5sum?   "-hdr 1" should result in VUI parameters being written to the SPS (sequence parameter set) within the HEVC file structure and thus the bitstreams should be different.  The encoded frames may still be the same content as the HDR informative is basically metadata and would not have an effect on the encoding.

**Comment by LSC527** [comment]
I tried the same command in SVT
./SvtHevcEncApp -i xx.yuv -w 1920 -h 1080 -b xx.mp4 -bit-depth 10 -encMode 5 -fps 25 -rc 1 -vid-info 1 -hdr 1

**Comment by tianjunwork** [comment]
Hi @LSC527 , `-hdr` is exposed in https://github.com/OpenVisualCloud/SVT-HEVC/issues/430. which according to the submitter, it works fine with HDR10 input.
And if you use `-hdr 1`, `VideoUsabilityInfo` is forced to 1. https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/Source/Lib/Codec/EbEncHandle.c#L2036. `-vid-info` is not needed.

**Comment by LSC527** [comment]
Thanks, @tianjunwork  @intelmark . I compare the output file with md5sum which shows that the files are different. But I still wonder why using SVT can cause difference in a video player while using SVT  cannot. 
Now I want to try this way mentioned in https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/README.md
![image](https://user-images.githubusercontent.com/34333110/85358644-d5f28380-b546-11ea-8163-f1f3d5258536.png)
but how do I output a file using this way?

**Comment by tianjunwork** [comment]
> Thanks, @tianjunwork @intelmark . I compare the output file with md5sum which shows that the files are different. But I still wonder why using SVT can cause difference in a video player while using SVT cannot.

what is context? which two cli output different bitstream with md5sum? Do do you have a bitstream parser to see if the vui is inserted for both bitstream?
 
> Now I want to try this way mentioned in https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/README.md
> ![image](https://user-images.githubusercontent.com/34333110/85358644-d5f28380-b546-11ea-8163-f1f3d5258536.png)
> but how do I output a file using this way?

Use `-b xxx.bin` to output hevc bitstream by SvtHevcEncApp. If you want to use mp4, please stick to ffmpeg.

**Comment by guojiansheng0925** [comment]
Hi @LSC527 , I have tried to reproduce the issue with following command:

> ffmpeg -y -s 1280x720 -pix_fmt yuv420p10le -i ~/content/Suzie_ProRes_1280x720_50f.p010.yuv -c:v libsvt_hevc -rc 1 -b:v 15M -preset 5 -hdr 1 out.h265

And there are vui parameters in the output stream:
![image](https://user-images.githubusercontent.com/58507250/86087949-efac4180-bad7-11ea-985c-857932aa3789.png)

But I didn't see the clear different color in both SvtHevcEncApp and SVT-FFmpeg with or without -hdr para. 
Could you please share your test sequence?
Which video player did you use?
And please check your software version of FFmpeg and SVT-HEVC.

Thanks.

**Comment by LSC527** [comment]
Thanks a lot for your attention @guojiansheng0925 !
I built SVT-HEVC ffmpeg_plugin following the instructions in [https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/README.txt ](url). I used master branch of SVT-HEVC and release/4.2 of ffmpeg according to the instructions. 
I used  video player named PotPlayer which can be found in [https://potplayer.org/](url).
So how can I cheak vui parameters in the output stream?

**Comment by guojiansheng0925** [comment]
Hi @LSC527 , you can use a bitstream parser to check if there is vui parameters.
For hevc, you can try the following tools:
Elecard HEVC Analyzer, 
ViCue Video Codec Analyzer

**Comment by LSC527** [comment]
Thanks, I try to output the h265 stream rather than mp4, and it works fine now.
