### ISSUE TITLE
Bitrate is too large

### ISSUE THREAD

**Issue by Dillon14281118** [OpenVisualCloud/SVT-HEVC#548]
Why the bitrate of svt-hevc is so large compared with x265?
I use CQP mode with qp={22,27,32,37} in svt-hevc and x265,the commands are as below:
./SvtHevcEncApp -i ../sc_desktop_1920x1080_60_8bit_420.yuv -w 1920 -h 1080 -n 90 -rc 0 -q 37 -fps 15 -b out.h265

![image](https://user-images.githubusercontent.com/22978904/85491373-fdf4ec00-b605-11ea-8cc3-eb4903955dff.png)

./x265 --input ../sc_desktop_1920x1080_60_8bit_420.yuv --frames 90 --input-res 1920x1080 --input-csp 1 --fps 15 --psnr --tune psnr --qp 37 -o out.h265
![image](https://user-images.githubusercontent.com/22978904/85491406-0fd68f00-b606-11ea-98b9-83bb23ac7991.png)

use ffmpeg to calc psnr:
./ffmpeg -r 15 -i out.h265 -s:v 1920x1080 -c:v rawvideo -pix_fmt yuv420p -r 15 -i ../sc_desktop_1920x1080_60_8bit_420.yuv -frames 90 -lavfi psnr="stats_file=psnr.log" -f null -

The BD-Rate result is as below(x265 is anchor):
![image](https://user-images.githubusercontent.com/22978904/85491498-3e546a00-b606-11ea-99cc-3c7346d4bf32.png)

We can found in the result that  the bitrate of svt-hevc is about twice that of x265 at the same level psnr.
Why the bitrate of svt-hevc is so high? How should I adjust the parameters?

**Comment by tianjunwork** [comment]
Hey @Dillon14281118 , thanks providing the data.
Encoders have their own ways to fine tune trade-off between speed and coding efficiency. It is meaningless to compare BD-rate between different trade-off configs(usually called preset). With default preset of x265 being `medium` and SVT-HEVC being `-encMode 7`, according to below preset mapping between x265 and SVT-HEVC, trade-off configs are not at the same level.
https://x265.readthedocs.io/en/default/svthevc.html#preset-option-mapping

FYI, link below shows the comparison of AV1/HEVC encoders.
https://www.compression.ru/video/codec_comparison/hevc_2019/

**Comment by Dillon14281118** [comment]
So the result in svt-hevc is normal?

**Comment by tianjunwork** [comment]
The PSNR curve is steadily decreasing for both SVT-HEVC and X265, from which I didn't see a warning sign.

**Comment by tianjunwork** [comment]
Hi @Dillon14281118 , anything to discuss further in this issue?
