### ISSUE TITLE
Got an error using x265 linked with SVT-HEVC to encode a 10bit input

### ISSUE THREAD

**Issue by LSC527** [OpenVisualCloud/SVT-HEVC#549]
I built SVT-HEVC with x265 and ran this command to encode a 10bit input:  x265 --svt --input xx.yuv --input-depth 10 --input-res 1920x1080 --fps 25 --output x265.mp4 
![image](https://user-images.githubusercontent.com/34333110/85525903-1aac1680-b63c-11ea-9bee-beb0811fb59c.png)
It said that "The encoder bit depth shall be equal to 8 for Main Profile"

**Comment by intelmark** [comment]
You might need to add a profile parameter for 10 bit encoding with x265
[https://x265.readthedocs.io/en/default/cli.html#profile-level-tier](url)

(e.g.) --main10

**Comment by LSC527** [comment]
THANKS！It works fine now.

**Comment by LSC527** [comment]
I wonder if I can: 
step 1: link SVT-HEVC with x265, as described in https://x265.readthedocs.io/en/latest/svthevc.html#build-steps
step 2: build FFMPEG with "./configure --enable-libx265"
step 3: enable SVT-HEVC through FFMPEG command

Now I have built FFMPEG with x265, which has been linked with SVT-HEVC. But I don't know what command/params should I use to enable SVT through FFMPEG.

**Comment by intelmark** [comment]
Are you able to encode an 8 bit file using X265's SVT option?

**Comment by tianjunwork** [comment]
Hi @LSC527 , using SVT_HEVC through x265 is out of scope of this project. Your question is related to interface between ffmpeg -> x265 -> SVT-HEVC.  Recommend you post question in x265 project.

**Comment by LSC527** [comment]
Thanks for your advice！
