### ISSUE TITLE
Library Crash for SlideShow_1280x720_20.yuv

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-HEVC#55]
The library crashes with the following command line:
SvtHevcEncApp -i SlideShow_1280x720_20.yuv -w 1280 -h 720  -tune 1 -encMode 8 

The crash is due to this secondSearchRegionIndexPosInteg going out of range.

**Comment by tianjunwork** [comment]
@dseah-intel is this issue still there? Could take care this one?

**Comment by dseah-intel** [comment]
@tianjunwork yes, we have a fix and it is next on my list to clear

**Comment by kelvinhu325** [comment]
@tianjunwork @hassount @intelmark  I tried it on my 8180 machine with SVT-HEVC master latest code (June 14), this test works well.

**Comment by intelmark** [comment]
Kelvin - retried with latest SVT-HEVC today.  The file encodes fine on my Linux NUC device, but still seeing crash on Windows.

**Comment by intelmark** [comment]
Retried with current SVT-HEVC head today.  Not seeing the crash anymore on Windows.

**Comment by PDX-Runner** [comment]
I tried with the latest code on windows with the below command. it still crashes. I build with Visual Studio 2017 into 64 bit. I think the search area address is out of bound. can somebody take a look into it?

-i SlideShow_1280x720.yuv -w 1280 -h 720 -asm 0 -lp 1 -encMode 0 -intra-period 100 -scd 0 -rc 0 -q 22 -n 100 -b SlideShow_1280x720_SVTMODE0_22_SVT.265
