### ISSUE TITLE
Memory Leak when running repeatedly in a process!

### ISSUE THREAD

**Issue by 13524182838** [OpenVisualCloud/SVT-HEVC#552]
I changed the example to add loop in main function and found it crashed at the iteration of 250.
The memory usage will arise along with the iteration.

### Code change:
Source/App/EbAppMain.c

`int32_t origin_main(int32_t argc, char* argv[]);`
`int32_t main(int32_t argc, char* argv[]) {`
`   for (int i = 0; i < 300; i++) {`
`            origin_main(argc, argv);`
`    }`
`    return 0;`
`}`
`/***************************************`
` * Encoder App Main`
` ***************************************/`
`int32_t origin_main(int32_t argc, char* argv[])`

### Test env:
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz , MemTotal:        8022952 kB

### Memory monitor:
![memory1f](https://user-images.githubusercontent.com/32996642/86309333-0e344900-bc4e-11ea-876b-cab946e7b1f8.png)
![memory100f](https://user-images.githubusercontent.com/32996642/86309342-13919380-bc4e-11ea-9a28-569d8e405e37.png)

**Comment by tianjunwork** [comment]
Hi @13524182838 thanks reporting the issue. There are a few global variables that take some memory in the app itself(not in the encoder library though). May I know what is the use case that `main()` is called repeatedly? 
Could you provide more info to help us reproduce? Is adding `origin_main` all your change? What is the command line used?

**Comment by 13524182838** [comment]
=> There are a few global variables that take some memory in the app itself(not in the encoder library though)
I think it is reasonable to keep some global objects. But it seems to be abnormal that the size of global objects will increase along with the loop iteration.
=> May I know what is the use case that main() is called repeatedly?
The use case is that we want to tune the best performance for the whole system(decode plus encode). So I need keep some cpu cores for decode and others for encode. What's the percentage for cpu affinity? We need to tune in iteration to figure out the best configuration. During the tuning, we find the memory leak issue.
=> Could you provide more info to help us reproduce? Is adding origin_main all your change? What is the command line used?
Yes. Our system is too complex. So I just use the example(Source/App/EbAppMain.c) and make least change to reproduce the issue. I just change the origin main function to new name 'origin_main' and add a loop to call origin main in the new main function (no more other changes). The command line is ./SvtHevcEncApp -i  Netflix_Boat_1920x1080_60fps_8bit_420_60f.yuv -w 1920 -h 1080 -n 100

**Comment by tianjunwork** [comment]
Hi @13524182838 , I examed the source code. 
Also changed the code like yours, then run valgrind on Linux `valgrind --leak-check=full --show-leak-kinds=all --tool=memcheck ./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.y4m -b out.bin -n 10` and vmmap on Windows. Either of the two show mem leak.
![image](https://user-images.githubusercontent.com/4551215/86415666-95001a80-bc7c-11ea-8dbd-4d64a74c1ca1.png)

If there is mem leak, it should show linear increase in your graph of RSS, should not be convergent.

**Comment by tianjunwork** [comment]
About setting thread affinity, I hope you noticed `-lp -ss` provided by encoder. And of cause there are `numactl` and `taskset`.

**Comment by 13524182838** [comment]
Tianjun,
=>Either of the two show mem leak.
You can finish the running for 300 iteration? Because in my code 'for (int i = 0; i < **300**; i++) {', it will crash at last in my side.

**Comment by tianjunwork** [comment]
The RSS memory is increasing slowly by iteration, not just after 300 iterations is done.
I tried with >10 iteration. Either of the two tools show mem leak.
Are you using master tip source code?

**Comment by 13524182838** [comment]
Tianjun,

=> Are you using master tip source code?
Yes we use the latest code on master:

commit ffb4e8dd744b4b9e44a5096fc64e5eb969611149 (HEAD -> master, origin/master, origin/HEAD)
Author: Jun <tianjun1.0@gmail.com>
Date:   Wed May 27 13:44:19 2020 -0700

    Add more details of header insertion in user guide (#538)

    Signed-off-by: Jun Tian <jun.tian@intel.com> 

=> I tried with >10 iteration. Either of the two tools show mem leak.
We tested on linux Ubuntu 16.04.3
97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Maybe you will encounter crash after 250 iteration.
Memory leak is my analysis from RSS for the root cause of crash. What I really concerned is the crash at iteration 250.

**Comment by intelmark** [comment]
@13524182838  - Is there any trace from the crash?

**Comment by tianjunwork** [comment]
Below is how I check RSS on Ubuntu. I don't think there is memory leak.
Are you checking only SvtHevcEncApp process?
```
(master) $ git diff
diff --git a/Source/App/EbAppMain.c b/Source/App/EbAppMain.c
index 5b64b5f..f9a6d13 100644
--- a/Source/App/EbAppMain.c
+++ b/Source/App/EbAppMain.c
@@ -75,11 +75,17 @@ void AssignAppThreadGroup(uint8_t targetSocket) {
 #endif
 }

-
+int32_t origin_main(int32_t argc, char* argv[]);
+int32_t main(int32_t argc, char* argv[]) {
+    for (int i = 0; i < 300; i++) {
+        origin_main(argc, argv);
+    }
+    return 0;
+}
 /***************************************
- * Encoder App Main
- ***************************************/
-int32_t main(int32_t argc, char* argv[])
+ * * Encoder App Main
+ * ***************************************/
+int32_t origin_main(int32_t argc, char* argv[])
 {
     if (GetSVTVersion(argc, argv) || GetHelp(argc, argv))
         return EB_ErrorNone;

checkrss() (
$* &>/dev/null &
pid="$!"
echo $pid
while sleep 5
do
    if ps -p $pid > /dev/null
    then
      grep VmRSS /proc/$pid/status
    else
        break
    fi
done
)
checkrss ./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.yuv  -h 1920 -w 1080 -n 100

VmRSS:   2660712 kB
VmRSS:   2685616 kB
VmRSS:   2689012 kB
VmRSS:   2695412 kB
VmRSS:   2700496 kB
VmRSS:   2700696 kB
VmRSS:   2700928 kB
VmRSS:   2701244 kB
VmRSS:   2701312 kB
VmRSS:   2701288 kB
VmRSS:   2701308 kB
VmRSS:   2701408 kB
VmRSS:   2701308 kB
VmRSS:   2701312 kB
VmRSS:   2701408 kB
VmRSS:   2701764 kB
VmRSS:   2701864 kB
VmRSS:   2701740 kB
VmRSS:   2701752 kB
VmRSS:   2701760 kB
VmRSS:   2701784 kB
VmRSS:   2701896 kB
VmRSS:   2701804 kB
VmRSS:   2701796 kB
VmRSS:   2701796 kB
VmRSS:   2701812 kB
VmRSS:   2701784 kB
VmRSS:   2700756 kB
VmRSS:   2700852 kB
VmRSS:   2700760 kB
VmRSS:   2700960 kB
VmRSS:   2700760 kB
VmRSS:   2701772 kB
VmRSS:   2700792 kB
VmRSS:   2701760 kB
VmRSS:   2701808 kB
VmRSS:   2701884 kB
VmRSS:   2702384 kB
VmRSS:   2703648 kB
VmRSS:   2703652 kB
VmRSS:   2703536 kB
VmRSS:   2703576 kB
VmRSS:   2703576 kB
VmRSS:   2703536 kB
VmRSS:   2703640 kB
VmRSS:   2703624 kB
VmRSS:   2703532 kB
VmRSS:   2703572 kB
VmRSS:   2703532 kB
VmRSS:   2703532 kB
```

**Comment by tianjunwork** [comment]
Hi @13524182838 , Jiangmin, any update on this issue?

**Comment by 13524182838** [comment]
jun,

Thanks a lot for your analysis.
We find it can be solved by calling malloc_trim in each iteration. :-)
