### ISSUE TITLE
Level 0 is incompatible with tier High

### ISSUE THREAD

**Issue by LeoKingLong** [OpenVisualCloud/SVT-HEVC#553]
1.Encode command：
SvtHevcEncApp -i 2_hd.yuv -w 7680 -h 3840 -fps 30 -intra-period 4 -irefresh-type 0 -vid-info 1 -rc 1 -tbr 62914560 -umv 0 -tile_slice_mode 1  -profile 1  -tier 1  -tile_row_cnt 12 -tile_col_cnt 12 -pred-struct 0 -b 2_hd.hevc

2.Problems :
-level default value is 0 ，**0 for auto determine Level**；
I think value 0 should compatible with tier High, but I got the error：
![image](https://user-images.githubusercontent.com/26246461/86343662-d815ba00-bc8b-11ea-94d1-9e5133cd48d8.png)

**Comment by tianjunwork** [comment]
@LeoKingLong , thank you reporting the issue. It is fixed by #554. Could you help verify also?

**Comment by LeoKingLong** [comment]
@tianjunwork 
I have tested it. It works.
Thanks.
