### ISSUE TITLE
How to add MCTS SEI ?

### ISSUE THREAD

**Issue by LeoKingLong** [OpenVisualCloud/SVT-HEVC#556]
hi~ @tianjunwork 
How to add mcts SEI info to hevc file ？
For example，Motion-constrained tile sets extraction information sets SEI message，thanks~
![image](https://user-images.githubusercontent.com/26246461/86898119-df7d0d80-c13a-11ea-8035-f92a20526b7b.png)

**Comment by tianjunwork** [comment]
Hi @LeoKingLong , currently we don't support inserting motion-constrained tile sets extraction information sets SEI message yet.

Hi @yanyings , do you use this SEI with SVT-HEVC in 360SCVP?

**Comment by yanyings** [comment]
Hi all,

We don’t add the motion-constrained tile sets extraction information sets SEI currently in 360SCVP. But we have added the RWPK, projection frame packing and viewport SEI in 360SCVP, maybe give you a reference.
https://github.com/OpenVisualCloud/Immersive-Video-Sample/tree/master/src/360SCVP

Thanks,
Yanying

**Comment by tianjunwork** [comment]
Thank you @yanyings providing the insight.

Hi @LeoKingLong , if your use case is 360 video streaming, 360SCVP library is a good example of utility that handles the hevc bitstream.
https://github.com/OpenVisualCloud/Immersive-Video-Sample/blob/master/src/doc/Immersive_Video_Delivery_360SCVP.md

SEI can be generated and written to elementary stream beyond the encoder. 360SCVP shows example how you can do it.
E.g. Omnidirectional viewport SEI message
```
I360SCVP_SetParameter(, ID_SCVP_PARAM_SEI_VIEWPORT, )
setViewportSEI
hevc_write_ViewportSEI
```

**Comment by tianjunwork** [comment]
Hi @LeoKingLong , any further questions on this topic?

**Comment by LeoKingLong** [comment]
> Hi @LeoKingLong , any further questions on this topic?

Thanks @tianjunwork ,no more questions .
