### ISSUE TITLE
Support for FFMPEG 4.3?

### ISSUE THREAD

**Issue by alatteri** [OpenVisualCloud/SVT-HEVC#561]
The ffmpeg patch instruction only mention support for 4.2.  Do the same patches work for 4.3, if not, any plan to support that?

Thanks.

**Comment by tianjunwork** [comment]
Hi @alatteri. Yeah, ffmpeg 4.3 is new tag. We haven't tested yet. If the patch applies, it should work.
Hi @guojiansheng0925 , could you take a look at ffmpeg 4.3? If plugin works, please also update the README in ffmpeg_plugin folder. Thank you.

**Comment by guojiansheng0925** [comment]
Hi @alatteri , I have checked that the current patch can apply for n4.3 and it works well. 
Hi @tianjunwork , I will update the README later.
Thanks.
