### ISSUE TITLE
Getting Illegal Instruction when running SVT-HEVC with ffmpeg on FreeBSD 11.2

### ISSUE THREAD

**Issue by Toys0125** [OpenVisualCloud/SVT-HEVC#573]
So i tried just pulling the port which installed and then followed the guide [https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/ffmpeg_plugin](url) which compiled, just tried using it. It would first pull about 30 frames then throw illegal operator. I then went and pulled ffmpeg from source port and then added in SVT-HEVC option to make file and compiled from that. Throws the same error at the same place. Then I used gdb on ffmpeg which shows.
```
Program received signal SIGILL, Illegal instruction.
0x00000008138bc19c in EbHevcPictureCopyKernelOutRaw_SSSE3 () from /usr/local/lib/libSvtHevcEnc.so.1
```
I know I have support for SSSE3 already here my full list
```
Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x29ee3ff<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,SMX,EST,TM2,SSSE3,CX16,xTPR,PDCM,PCID,DCA,SSE4.1,SSE4.2,POPCNT,AESNI>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x1<LAHF>
  Structured Extended Features3=0x9c000000<IBPB,STIBP,L1DFL,SSBD>
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x29ee3ff<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,SMX,EST,TM2,SSSE3,CX16,xTPR,PDCM,PCID,DCA,SSE4.1,SSE4.2,POPCNT,AESNI>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x1<LAHF>
  Structured Extended Features3=0x9c000000<IBPB,STIBP,L1DFL,SSBD>
```

**Comment by tianjunwork** [comment]
Hi @Toys0125 , SVT-HEVC doesn't run without avx2 instruction set. 
` the encoder runs on any 5th Generation Intel Core™ Processors (formerly Broadwell) CPUs (Xeon E5-v4) or newer.` which means the processor at least should support avx2 .
