### ISSUE TITLE
Request release version of SVT-HEVC that supports ffmpeg n4.4

### ISSUE THREAD

**Issue by akwrobel** [OpenVisualCloud/SVT-HEVC#592]
The current release revision of SVT-HEVC v1.5.0 ffmpeg-plugin does not support the latest version of ffmpeg n4.4.  
Based on a previous issue a new patch was added that does provide this support, this is a request for a release which includes this update.  

Previous issue with fix:
https://github.com/OpenVisualCloud/SVT-HEVC/issues/590

**Comment by tianjunwork** [comment]
Hi @akwrobel , 1.5.1 release is out there to support ffmpeg n4.4.
