### ISSUE TITLE
ffmpeg-master: patch no longer compiles

### ISSUE THREAD

**Issue by 1480c1** [OpenVisualCloud/SVT-HEVC#598]
commit 56e9e0273a79fb4ff4276503e69981f8e383f22b in FFmpeg removed ff_alloc_packet2 and replaced it with ff_alloc_packet

**Comment by tianjunwork** [comment]
Hi Chris, Thank you for reporting the issue. The conflict is only for SVT-HEVC plugin or both(vp9)?

**Comment by 1480c1** [comment]
It doesn't seem like that function is used in svt-vp9's wrapper

**Comment by tianjunwork** [comment]
Thanks Chris.
Hi @guojiansheng0925, could you rebase the plugin patch on ffmpeg master? Thank you.
