### ISSUE TITLE
libsvt_hevc has the problem to output the resolution 720x1280

### ISSUE THREAD

**Issue by ailuo2019** [OpenVisualCloud/SVT-HEVC#601]
ffmpeg -y -c:v h264_cuvid -i xxxx_264_1920x1080.mp4 -c:a copy -c:v libsvt_hevc -vf scale=w=720:h=1280 vertical.mp4
 It gives me a segmentation fault.
Output #0, mp4, to 'vertical.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: hevc (hev1 / 0x31766568), yuv420p(tv, progressive), 720x1280 [SAR 32:9 DAR 2:1], q=2-31, 7000 kb/s, 29.97 fps, 30k tbn (default)
    Metadata:
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc58.134.100 libsvt_hevc
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]
Segmentation fault0 q=0.0 size=       0kB time=00:00:00.06 bitrate=   5.5kbits/s speed=   3x  

It worked fine if I use the encoder hevc_nvenc. The input file I used is h264 HD file, 1920x1080.

**Comment by ailuo2019** [comment]
The input file I used is h264 HD file, 1920x1080.

**Comment by tianjunwork** [comment]
Hi @ailuo2019 , Thanks reporting the issue. But I didn't reproduce with another 1080p source file.
1. Could you try to find the call stack when it crashes?
2. If the crash is from SVT-HEVC, is it source file related? Could you try another file?
![image](https://user-images.githubusercontent.com/4551215/122629235-57082c00-d070-11eb-8117-54fb8e64507d.png)

**Comment by ailuo2019** [comment]
Hi, the input I used is not a YUV file, is a .mp4 file. Would you please
try that? Maybe the problem is triggered in the transcoding.

**Comment by tianjunwork** [comment]
Hi @ailuo2019 , SVT library is only an encoder. No matter what source format, input to encoder is always decoded YUV frame. Since I didn't see crash with y4m source, it may not be encoder to blame.
Could you run gdb to get the backtrace after crash?
