### ISSUE TITLE
Equirectangular projection ERP

### ISSUE THREAD

**Issue by MisterNixon** [OpenVisualCloud/SVT-HEVC#605]
Hi, I and my team are working on a project and we want to be able to change the tile encoding to an ERP with SVT-HEVC on the OWT server client. We don't know exactly where to look to do some modifications in the source code. We are very new to video streaming. Our main goal is to be able to stream a 360-3d (stereo) video in 8k. FYI it's for a school project. Thank you!

**Comment by tianjunwork** [comment]
Hi @MisterNixon , not sure if you got your answer. SVT-HEVC can be used to encode either ERP or cubemap format 360 video. Tiling is a encoder feature. It has nothing to do with 360 video format. Let me know if you need help with encoder parameters.

**Comment by MisterNixon** [comment]
To help us through this process, our goal is to be able to encode a 360 video using Cubemap encoding, connect a 360-3D 8k camera to the OWT-server for live streaming and enable a stereoscopic view (top-bottom). We have found this file (https://github.com/PFE-023-E2021/owt-server/blob/360-video/source/core/owt_base/SVTHEVCMCTSEncoder.cpp) in the owt-server / branch 360-video, we believe this file is responsible for making the tiles?

If we understand properly, the projection does not matter to the encoder. The server simply selects the appropriate tiles according to the FOV and the projection, then the player generates the appropriate image. Can you confirm?

Finally, if you could help us with encoder parameters to be able to encode with Cubemap, it would be very much appreciated! 

Thank you!

**Comment by tianjunwork** [comment]
Hi @MisterNixon , a 360 video streaming pipeline is similar to a typical live streaming pipeline:
camera -> on premise process/encode -> cloud ingestion -> decoder -> SVT-HEVC encoder -> origin -> CDN -> client
Based on my knowledge, 360 video camera produces ERP format, it can be transformed to CMP on premise. Encoder(e.g. SVT-HEVC) on cloud get decoded CMP, then encode to HEVC bitstream using MCTS(using motion-constrained tile sets), which is needed by viewport-adaptive methods of 360 video streaming.
For tile-based encoder setting, set `TileRowCount, TileColumnCount` based on your CMP format, and `UnrestrictedMotionVector: For MCTS support, set -umv 0`. The reset is the same for regular encode.

**Comment by MisterNixon** [comment]
Hi @tianjunwork, we found a code line indicating the type of projection. On the other hand, we did change the parameter with E_SVIDEO_CUBEMAP by creating a fork of the project but the build failed as you can see here: https://github.com/PFE-023-E2021/owt-server/commit/29a6e7be91326bcee5ea38e03b6b2c65ab46e3db. 

We are still looking for a way to enable a stereoscopic view. Could you help us with that?
Thank you!

**Comment by tianjunwork** [comment]
Hi @MisterNixon , I am afraid your request is out of the scope of the support of this repo. If there is a business interest with 360 video streaming product, I can make the connection with our 360 video streaming team.
