### ISSUE TITLE
EbInitEncoder takes too much time [ >10s ]

### ISSUE THREAD

**Issue by ai0376** [OpenVisualCloud/SVT-HEVC#609]
cpu: intel xeon gold 6239 @2.10GHz
memory: 190G

**Comment by tianjunwork** [comment]
Hi @ai0376 , how you use the encoder, by ffmpeg or sample app? What is your command line or parameters?

**Comment by ai0376** [comment]
@tianjunwork  owt-server  use  initDefaultParameters  https://github.com/open-webrtc-toolkit/owt-server/blob/master/source/core/owt_base/SVTHEVCEncoder.cpp

**Comment by tianjunwork** [comment]
```
    initDefaultParameters();
    updateParameters(width, height, frameRate, bitrateKbps, keyFrameIntervalSeconds);
```
I can read the default parameters, but I don't know the value for the updated ones. Could you use debug build of svt hevc library which prints information like below?
![image](https://user-images.githubusercontent.com/4551215/130277671-8f94f292-8342-4b81-a314-7a936e869cca.png)

Other questions:
1. Which release of library you used?
2. How did you measure EbInitEncoder time?
3. Could you try our sample app if possible? Feel free to set parameter value in `Source/App/EbAppConfig.c` EbConfigCtor(). And simply do `-i yuv_file -w width -h height(the rest parameters will be taken from EbConfigCtor) through the command line. In this way, we can simulate how OWT uses svt library, which makes it easier for me to debug.
