### ISSUE TITLE
Audio Sync issue

### ISSUE THREAD

**Issue by puligclone** [OpenVisualCloud/SVT-HEVC#611]
Hi, when i try to mux audio to the converted file using ffmpeg it gives a timestamp error. Iam able to mux it with mkvtoolnix but the audio plays out of sync. Tried with many files using below command but always same issue

ffmpeg -y -hide_banner -stats -loglevel error -i "input.mkv" -map 0:0 -an -sn -pix_fmt yuv420p10le -strict -1 -vsync 0 -nostdin -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -n 10775 -rc 0 -q 22 -max-qp 35 -encMode 5 -profile 2 -umv 1 -brr 1 -tile_col_cnt 1 -tile_row_cnt 4 -tile_slice_mode 1 -tpic 1 -fpsinvps 1 -intra-period 245 -vid-info 1 -bit-depth 10 -color-format 1 -b "out.265"

**Comment by tianjunwork** [comment]
Hi @puligclone , Could you try SVT-HEVC ffmpeg plugin directly? https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/ffmpeg_plugin

**Comment by puligclone** [comment]
> Hi @puligclone , Could you try SVT-HEVC ffmpeg plugin directly? https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/ffmpeg_plugin

no issues with ffmpeg plugin. but it has fewer options and cant pass hdr parameters like cll and master display.

**Comment by tianjunwork** [comment]
Glad to know no A/V sync issue with plugin. Yes, the plugin doesn't expose all the interfaces.

**Comment by tianjunwork** [comment]
Hi @puligclone, is there anything else we can help with on this topic?

**Comment by puligclone** [comment]
> Hi @puligclone, is there anything else we can help with on this topic?

No, Thank you.
