### ISSUE TITLE
FFmpeg patch error

### ISSUE THREAD

**Issue by FreddyX078** [OpenVisualCloud/SVT-HEVC#614]
Hi,

Applying ffmpeg-patch to latest ffmpeg-master result in an error: 

Updating files: 100% (7699/7699), done.
patching file configure
Hunk #1 succeeded at 289 (offset 1 line).
Hunk #2 succeeded at 1814 (offset 21 lines).
Hunk #3 succeeded at 3376 (offset 59 lines).
Hunk #4 succeeded at 6671 (offset 133 lines).
patching file libavcodec/Makefile
Hunk #1 succeeded at 1093 (offset 29 lines).
patching file libavcodec/allcodecs.c
Hunk #1 FAILED at 774.
1 out of 1 hunk FAILED -- saving rejects to file libavcodec/allcodecs.c.rej
patching file libavcodec/libsvt_hevc.c

Hope someone will fix it.
Thanks.

**Comment by tianjunwork** [comment]
Hi @FreddyX078 , I am assuming you tried to apply master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch.
Hi @guojiansheng0925 Jiansheng, could you take a look? Thank you.

**Comment by guojiansheng0925** [comment]
Hi @tianjunwork , I have updated the patch for master branch. Could you please review and merge it, thanks.

**Comment by FreddyX078** [comment]
Hi thanks, new patch is working!
Great job!
