### ISSUE TITLE
FFMPEG compile failing again

### ISSUE THREAD

**Issue by alatteri** [OpenVisualCloud/SVT-HEVC#616]
Hello,

It seems the latest master of FFMPEG is failing to compile with libsvthevc again.
FFMPEG-4fbf3c828b63a782bd6730427f376f10809b99a8
SVT-HEVC-6e677e0017cb27bfdd62effcfd2a0dc83b48bb16

patch has been applied: git apply -3 SVT-HEVC/ffmpeg_plugin/master-*.patch

./configure --enable-gpl --enable-nonfree --enable-static --enable-shared --enable-pic --enable-libfdk-aac --enable-libx264 --enable-libopus --enable-libsvthevc --enable-libx265 --enable-libsrt --enable-decklink --enable-libmfx

libavcodec/libsvt_hevc.c:571:6: error: ‘FFCodec’ {aka ‘struct FFCodec’} has no member named ‘encode2’
  571 |     .encode2        = eb_encode_frame,
      |      ^~~~~~~
libavcodec/libsvt_hevc.c:571:23: warning: initialization of ‘int (*)(struct AVCodecContext *, struct AVFrame *, int *, struct AVPacket *)’ from incompatible pointer type ‘int (*)(AVCodecContext *, AVPacket *, const AVFrame *, int *)’ {aka ‘int (*)(struct AVCodecContext *, struct AVPacket *, const struct AVFrame *, int *)’} [-Wincompatible-pointer-types]
  571 |     .encode2        = eb_encode_frame,
      |                       ^~~~~~~~~~~~~~~
libavcodec/libsvt_hevc.c:571:23: note: (near initialization for ‘ff_libsvt_hevc_encoder.cb.decode’)
make: *** [ffbuild/common.mak:78: libavcodec/libsvt_hevc.o] Error 1

**Comment by tianjunwork** [comment]
It seems that there are some frequent changes on upstream master branch recently. I am not sure when the change will be stable. To avoid frequent rebase SVT-HEVC ffmpeg patch with unfinished feature in upstream, we will track the update on ffmpeg and probably won't fix this conflict right away. 
Could you use n4.4 instead first?

**Comment by tianjunwork** [comment]
Hi @guojiansheng0925, could you track the update on ffmpeg upstream? When the feature is stable, we can rebase the master patch. Thank you.

**Comment by guojiansheng0925** [comment]
Hi @tianjunwork , I just create a draft [PR#617](https://github.com/OpenVisualCloud/SVT-HEVC/pull/617).
And I will update and mark it ready when the feature is stable.

@alatteri Besides n4.4, you may use the patch in [PR#617](https://github.com/OpenVisualCloud/SVT-HEVC/pull/617) temporary.

thanks.
