### ISSUE TITLE
Could Not Allocate Enough Memory For Channel 1

### ISSUE THREAD

**Issue by wpss929** [OpenVisualCloud/SVT-HEVC#620]
I‘ve got some problem trying to use SvtHevcEncApp for a 8K yuv sample’s coding. It reported that “allocate memory failed…Could not allocate enough memory for channel 1”
My project is under win10 and vs2019. With about 8GB memory left, I don’t think the reason is my computer.

**Comment by 1480c1** [comment]
Hi, according to the table on https://github.com/OpenVisualCloud/SVT-HEVC#hardware the recommended ram for encoding a 8k 10-bit stream is 64 GiB

encoding a 10-bit 8k 100 frame sample on my machine takes about 16012396 kilobytes, or 16 gigabytes

Can you confirm your system configuration?

**Comment by 1480c1** [comment]
No response in a while, we can reopen if you encounter this again
