### ISSUE TITLE
Is it possible to control bitrate by frame or window level?

### ISSUE THREAD

**Issue by htliu6** [OpenVisualCloud/SVT-HEVC#623]
Hi everyone,
    I am new to SVT-HEVC, and wonder whether it is possible to control the output bitrate by frame or window (several frames) level?
    Looking forwards to your reply!

**Comment by 1480c1** [comment]
Hi @htliu6,

From what I know about the code at this time, the only way to control the bitrate of individual frames is to use the QpFile option, so `-use-q-file 1 -qp-file qps.txt` where qps.txt is a file that contains qps separated by newlines for each individual frame. That option unfortunately does not give you granular control over the exact bitrate, but can give you a good starting point.

**Comment by 1480c1** [comment]
Assuming there's nothing left to be said here
