### ISSUE TITLE
Patching ffmpeg failed -> solution

### ISSUE THREAD

**Issue by FreddyX078** [OpenVisualCloud/SVT-HEVC#627]
Hi, after Apple released there updated xcode for Ventura, I ran my script to build ffmpeg with SVT-HEVC.

Unfortunately the patch failed.
But it was easy to fix and I've attached the new patch.

Maybe you will check and fix it in the repo.

Thank you.

[master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.txt](https://github.com/OpenVisualCloud/SVT-HEVC/files/9913958/master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.txt)

**Comment by 1480c1** [comment]
Hi @FreddyX078, would you be able to open a PR for that instead?

**Comment by FreddyX078** [comment]
Never done it before and it looks a bit complicated to me. Will investigate later, but at the moment I have not much time unfortunately :-(
