### ISSUE TITLE
FFMPEG: Couldn't apply patch for SVT-HEVC encoder while building FFMPEG for 64 bit Windows.

### ISSUE THREAD

**Issue by classicdoomenjoyer** [OpenVisualCloud/SVT-HEVC#645]
6:25:04   Running git clone for ffmpeg...
16:30:23   Running git update for ffmpeg...
16:30:59 ┌ ffmpeg git  ............................... [Recently updated]
16:30:59 ├ Changing options to comply to gplv3...
master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
        Patch could not be applied with `git am`. Continuing without patching.
16:31:37 ├ Compiling static FFmpeg...
16:31:40 ├ Running configure...
16:37:09 ├ Running make...

When I was building FFMPEG with help of Media Autobuild Suite, I ran into this problem, and the resulting FFMPEG.exe didn't had `libsvthevc` encoder.

Can you please fix this ?

**Comment by 1480c1** [comment]
Fixed with https://github.com/OpenVisualCloud/SVT-HEVC/commit/78bcaa7bdefa0dd593149517ce41842d528d596f

**Comment by classicdoomenjoyer** [comment]
> Fixed with [78bcaa7](https://github.com/OpenVisualCloud/SVT-HEVC/commit/78bcaa7bdefa0dd593149517ce41842d528d596f)

Thank you so much Sir/Madam 🙏
