### ISSUE TITLE
[RFC]  is it have plan to support other input pixel format.

### ISSUE THREAD

**Issue by mypopydev** [OpenVisualCloud/SVT-HEVC#8]
Encoding 100 NV12 format frames with VBR mode with cmd:

./HevcEncoderApp  -i ~/Videos/1920_1080_100fames.yuv -w 1920 -h 1080 -intra-period 249 -irefresh-type 2 -rc 1 -vid-info 1 -tune 0 -tbr 4000000 -profile 1 -level 4.1 -tier 0 -fps 30 -encMode 9 -hierarchical-levels 3 -b test.h265

then use ffplay check test.h265, found the context is wrong. 

the commit dc6c63706117cc4c2324650f6f2dbee857ad4818 (mainline/master)

But YUV420P is Ok for this case.

So, is it have plan to support other input pixel format for nv12 or other format ?

**Comment by hassount** [comment]
@mypopydev 
Thank you for your feedback. 
the NV12 format is currently not supported for SVT-HEVC and is not on the road map for upcoming releases; however, we welcome contributions for such support.

**Comment by tsubasawing123456** [comment]
And how about the packed YUV formats? Not on the road map, either?

**Comment by tianjunwork** [comment]
@tsubasawing123456 Thank you for your feedback. You can checkout our road map here: https://trello.com/b/0xqT4xeY/svt-hevc. We welcome contributions for packed YUV formats support.

**Comment by lijing0010** [comment]
Only support planar yuv support, no plan for packed yuv input
