### ISSUE TITLE
Convert user guide to Markdown

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-HEVC#95]
An user guide in markdown would be much easier to maintain.

 - [x] Upload original user guide (.docx I think?)
 - [x] Convert user guide to Markdown (using [word-to-markdown](https://word-to-markdown.herokuapp.com/) and/or [Pandoc](https://pandoc.org/) for example).
 - [x] Check Markdown file on errors
 - [x] Upload to user guide in Markdown GitHub

**Comment by hassount** [comment]
@EwoutH 
Agreed, thank you for suggesting the conversion tool, we'll work on addressing this asap

**Comment by 1480c1** [comment]
Are there anymore docs/user guides?

**Comment by EwoutH** [comment]
Nope, this issue can be closed indeed.
