### ISSUE TITLE
Question on AVX512 instruction

### ISSUE THREAD

**Issue by edisongjs** [OpenVisualCloud/SVT-HEVC#96]
Question is on ffmpeg plugin. Is it on by default if it runs on skylake? Is there any way to disable AVX512 instruction for SVT HEVC encoder?

**Comment by tianjunwork** [comment]
There is a global variable “ASM_TYPE” in EbEncHandle.c, also a function GetCpuAsmType() to decide which instruction set can be used at run time. So yes, AVX512 is on for skylake. You can look into GetCpuAsmType().

**Comment by tianjunwork** [comment]
@edisongjs encoder has a api called AsmType(-asm). Assembly instruction set 
(0: C Only, 1: Automatically select highest assembly instruction set supported). If it is not exposed by ffmpeg, you could make a request or add it by yourself.

**Comment by tianjunwork** [comment]
Hi @jsunintel, please see if you can take care of this issue. Thx.

**Comment by jsunintel** [comment]
@edisongjs do you need an interface? SvtHevcAPP doesn't have such an interface either.

**Comment by tianjunwork** [comment]
@jsunintel I think this is the interface needed to expose by ffmpeg plugin: AsmType(-asm)

**Comment by edisongjs** [comment]
It would be good to have such interface.

**Comment by jsunintel** [comment]
> 
> 
> It would be good to have such interface.

This request is under consideration.
